// Seed data for 14 additional Industries pages. Content mirrors
// client/src/constants/industries.ts (the IndustryPageContent fallback data)
// so the CMS-driven page and the reversible legacy fallback show identical
// content. Companion to newSolutionsData.ts / newServicesData.ts, following
// the same block-array pattern already used for the 6 original Industries
// pages (see "industries-automotive" in seedData.ts).

interface IndustryContent {
    hero: { label: string; title: string; description: string; image: string };
    mission: { label: string; title: string; description: string };
    stats: { label: string; title: string; description: string; items: { value: number; suffix: string; label: string }[] };
    howHelp: { title: string; subtitle: string; items: { title: string; image: string; href: string }[] };
    builtToDeliver: { title: string; subtitle: string; points: { icon: string; title: string; description: string }[] };
    video: { label: string; title: string; description: string; videoUrl: string };
    services: { title: string; subtitle: string; items: { title: string; description: string; image: string; href: string }[] };
    faqs: { title: string; items: { question: string; answer: string }[] };
    cta: { title: string; description: string; btnText: string; btnHref: string; bgImage: string };
}

function buildIndustryPage(slug: string, navLabel: string, c: IndustryContent) {
    return {
        slug: `industries-${slug}`,
        title: `Industries — ${navLabel}`,
        status: 'published' as const,
        seo: {},
        blocks: [
            { blockType: 'industry-hero', order: 0, anchorId: 'hero', data: c.hero },
            {
                blockType: 'sticky-nav', order: 1, data: {
                    navItems: [
                        { id: 'hero', label: 'Overview' },
                        { id: 'solutions', label: 'Solutions' },
                        { id: 'capabilities', label: 'Capabilities' },
                        { id: 'services', label: 'Services' },
                        { id: 'faqs', label: 'FAQs' },
                    ]
                }
            },
            { blockType: 'mission-section', order: 2, anchorId: 'mission', data: { label: c.mission.label, title: c.mission.title, bodyText: c.mission.description } },
            { blockType: 'stats-section', order: 3, anchorId: 'stats', data: { label: c.stats.label, title: c.stats.title, description: c.stats.description, stats: c.stats.items } },
            { blockType: 'how-we-can-help', order: 4, anchorId: 'solutions', data: { title: c.howHelp.title, subtitle: c.howHelp.subtitle, items: c.howHelp.items } },
            { blockType: 'built-to-deliver', order: 5, anchorId: 'capabilities', data: { title: c.builtToDeliver.title, subtitle: c.builtToDeliver.subtitle, points: c.builtToDeliver.points } },
            { blockType: 'video-teaser', order: 6, anchorId: 'video', data: c.video },
            { blockType: 'services-section', order: 7, anchorId: 'services', data: { title: c.services.title, subtitle: c.services.subtitle, services: c.services.items } },
            { blockType: 'faq-section', order: 8, anchorId: 'faqs', data: c.faqs },
            { blockType: 'cta-banner-industry', order: 9, anchorId: 'cta', data: c.cta },
        ],
    };
}

const CTA_BG = 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1920&q=80';

const AUTO_COMPONENTS: IndustryContent = {
    hero: { label: 'Auto Components Industry', title: 'Reliable Steel for Auto Component Manufacturing', description: "We supply certified CR and HR steel to auto component manufacturers producing brackets, chassis parts, and precision-stamped assemblies for the automotive supply chain.", image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Powering the Component Supply Chain', description: 'Auto component manufacturers need consistent gauge, grade, and finish to keep stamping and welding lines running without interruption. We supply certified CR and HR steel matched to your tooling and tolerance requirements.' },
    stats: { label: 'Impact', title: 'Precision at Scale', description: "Supporting component manufacturers across Northern India's auto belt.", items: [{ value: 8, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 15, suffix: '+', label: 'Component makers served' }, { value: 48, suffix: 'hr', label: 'Standard dispatch window' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for auto component manufacturers.', items: [{ title: 'Grade Matching for Stamped Parts', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Slit Coil Supply', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Scheduled Bulk Delivery', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }, { title: 'Quality Certification', image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&q=80', href: '/steel-procurement' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Tolerance-matched steel and production-paced delivery for component manufacturing lines.', points: [{ icon: 'Settings2', title: 'Tolerance-matched supply', description: 'Steel sized and finished to match your press tooling, reducing setup changes and scrap.' }, { icon: 'TrendingUp', title: 'Production-paced delivery', description: 'Scheduled deliveries aligned to your stamping line cadence, not just standard freight windows.' }, { icon: 'Globe', title: 'Certified traceability', description: 'Every batch backed by a Manufacturer Test Certificate for full component traceability.' }] },
    video: { label: 'IN MOTION', title: 'Keeping Component Lines Running', description: 'See how scheduled CR coil delivery keeps a stamping line moving without downtime.', videoUrl: 'https://cdn.pixabay.com/video/2021/01/24/62900-504780516_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: "Support built around your press line's cadence, from grade selection to scheduled delivery.", items: [{ title: 'Slit Coil Supply', description: 'Coils slit to your exact stamping width, reducing scrap and setup time on the press line.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Grade & Finish Selection', description: "Technical support to match CR/HR grade and surface finish to your part's forming and finish requirements.", image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Scheduled Bulk Delivery', description: 'Recurring delivery schedules that match your production plan, reducing on-site inventory.', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    faqs: { title: 'FAQs', items: [{ question: 'What CR/HR grades suit auto component stamping?', answer: 'Commercial (D), Drawing (DD), and Extra Deep Drawing (EDD) CR grades under IS 513 are most common, depending on the depth and complexity of your stamped part.' }, { question: 'Can you supply pre-slit coil for our press line?', answer: 'Yes, our processing facility slits master coils to your exact width, ready to load directly onto your stamping line.' }, { question: 'Do you provide test certificates for every batch?', answer: 'Yes, every batch is sourced directly from SAIL and comes with a Manufacturer Test Certificate for full traceability.' }, { question: 'What is your minimum order quantity?', answer: 'We work with both bulk mill-direct orders and smaller processed-coil quantities — talk to our team about your specific volume.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get consistent, certified steel supply for your auto component production line.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const ELECTRICAL_PANEL: IndustryContent = {
    hero: { label: 'Electrical Panel Industry', title: 'Precision CR Steel for Electrical Panel Manufacturing', description: 'We supply Cold Rolled steel sheets and coils for electrical panel enclosures, switchgear boxes, and control cabinets requiring clean, paintable surfaces.', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Enclosures Built on Consistent Steel', description: 'Panel builders need flat, defect-free CR sheet that powder-coats evenly and forms cleanly on the brake press. We supply skin-passed CR steel suited to enclosure fabrication.' },
    stats: { label: 'Impact', title: 'Consistent Quality, Every Batch', description: 'Supporting electrical panel and enclosure fabricators with reliable CR steel.', items: [{ value: 6, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 20, suffix: '+', label: 'Panel fabricators served' }, { value: 99.5, suffix: '%', label: 'On-time dispatch' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for electrical panel and enclosure manufacturers.', items: [{ title: 'CR Sheet for Enclosures', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/steel-procurement' }, { title: 'Precision Shearing & Slitting', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Surface Finish Selection', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Scheduled Delivery', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Clean, paint-ready CR steel processed to enclosure specification.', points: [{ icon: 'ShieldCheck', title: 'Clean, paintable surface', description: 'Skin-passed CR steel finished for even powder-coat and paint adhesion on enclosure panels.' }, { icon: 'Settings2', title: 'Brake-press-ready sheet', description: 'Sheared and slit to your exact enclosure dimensions, reducing in-house prep work.' }, { icon: 'TrendingUp', title: 'Reliable repeat supply', description: "Consistent gauge and finish batch to batch, so enclosure quality doesn't vary with the steel source." }] },
    video: { label: 'IN MOTION', title: 'Precision Sheet for Precision Enclosures', description: 'See how cut-to-size CR sheet speeds up panel fabrication from blank to brake press.', videoUrl: 'https://cdn.pixabay.com/video/2018/11/02/19084-297771746_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Support built around your enclosure fabrication line, from finish selection to cut-to-size sheet.', items: [{ title: 'Cut-to-Size CR Sheet', description: 'Sheet sheared to your enclosure dimensions, ready for forming without secondary trimming.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Surface Finish Consultation', description: 'Guidance on skin-passed and finish grades suited to powder coating and painting.', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Recurring Supply Scheduling', description: 'Delivery scheduled against your panel production plan to reduce on-site steel inventory.', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    faqs: { title: 'FAQs', items: [{ question: 'Which CR grade is best for panel enclosures?', answer: 'Commercial (D) or Drawing (DD) grade CR sheet under IS 513 is typically sufficient for enclosure forming and bending.' }, { question: 'Can you shear sheet to our exact panel dimensions?', answer: 'Yes, our processing facility shears and slits to your specified dimensions before dispatch.' }, { question: 'Does the surface finish support powder coating?', answer: 'Yes, our skin-passed CR sheet provides a clean, consistent surface suited to powder coat and paint adhesion.' }, { question: 'What thickness range do you supply?', answer: "We supply CR sheet across the standard gauge range used for panel and enclosure fabrication — share your specification and we'll confirm availability." }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get consistent, paintable-grade CR steel for your enclosure production line.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const FURNITURE: IndustryContent = {
    hero: { label: 'Furniture Industry', title: 'Cold Rolled Steel for Modern Steel Furniture', description: 'We supply CR sheet and coil for office furniture, modular storage, and steel furniture manufacturing that needs a smooth, weldable, paint-ready surface.', image: 'https://images.unsplash.com/photo-1518005020951-ecc84916723c?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Steel That Shapes Everyday Design', description: 'From modular office systems to steel storage units, furniture manufacturers need consistent CR steel that welds cleanly and finishes well. We supply grade and gauge matched to your product line.' },
    stats: { label: 'Impact', title: 'Design-Grade Consistency', description: 'Supporting steel furniture manufacturers with reliable CR steel supply.', items: [{ value: 5, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 18, suffix: '+', label: 'Furniture manufacturers served' }, { value: 72, suffix: 'hr', label: 'Standard dispatch window' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for steel furniture manufacturers.', items: [{ title: 'CR Sheet & Coil Supply', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/steel-procurement' }, { title: 'Cut-to-Length Processing', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Finish & Gauge Selection', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Bulk Order Scheduling', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Weld-ready CR steel matched to your furniture design and production volume.', points: [{ icon: 'Settings2', title: 'Weld-ready sheet', description: 'Clean-surfaced CR steel that welds and finishes consistently across production runs.' }, { icon: 'TrendingUp', title: 'Design-matched gauge', description: "Steel sized to your product's structural and aesthetic requirements, from light gauge panels to structural frames." }, { icon: 'Globe', title: 'Dependable bulk supply', description: 'Recurring bulk orders scheduled to match your manufacturing calendar.' }] },
    video: { label: 'IN MOTION', title: 'From Coil to Cabinet', description: 'See how cut-to-length CR steel moves from raw coil to finished steel furniture.', videoUrl: 'https://cdn.pixabay.com/video/2022/10/25/136365-764353842_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Support built around your furniture production line, from cutting to scheduled delivery.', items: [{ title: 'Cut-to-Length Supply', description: 'Sheet cut to your exact panel and frame lengths, reducing in-house cutting and waste.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Grade & Gauge Matching', description: 'Technical guidance to match CR grade and thickness to your furniture design requirements.', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Bulk & Recurring Delivery', description: 'Scheduled bulk delivery aligned to your production runs.', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    faqs: { title: 'FAQs', items: [{ question: 'What CR grade works best for steel furniture?', answer: 'Commercial (D) grade CR sheet under IS 513 is typically sufficient for most furniture panels and frames; drawing grades are available for deeper-formed components.' }, { question: 'Can you cut sheet to our exact panel size?', answer: 'Yes, our processing facility cuts to length and shears to your specified dimensions.' }, { question: 'Do you supply both sheet and coil?', answer: 'Yes, we supply CR steel in both coil and sheet form depending on your production setup.' }, { question: 'What is the typical lead time?', answer: 'Standard grades in stock typically dispatch within 2-3 days; bulk or custom-processed orders are scheduled around your production calendar.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get consistent, weld-ready CR steel for your furniture production line.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const HVAC: IndustryContent = {
    hero: { label: 'HVAC Industry', title: 'Galvanized-Ready Steel for HVAC Manufacturing', description: 'We supply CR and HR flat steel for ducting, casings, and structural components used in HVAC equipment and ductwork manufacturing.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Steel Behind Climate Control Systems', description: 'HVAC manufacturers depend on consistent gauge and flatness for ducting and casing fabrication. We supply CR and HR steel suited to forming, bending, and welding HVAC components.' },
    stats: { label: 'Impact', title: 'Precision-Formed, Every Time', description: 'Supporting HVAC ducting and casing manufacturers across Northern India.', items: [{ value: 7, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 16, suffix: '+', label: 'HVAC manufacturers served' }, { value: 48, suffix: 'hr', label: 'Standard dispatch window' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for HVAC equipment and ductwork manufacturers.', items: [{ title: 'Sheet & Coil Supply', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/steel-procurement' }, { title: 'Cut-to-Length & Slitting', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Grade Selection Support', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Scheduled Delivery', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Forming-ready CR and HR steel processed for ducting and casing production.', points: [{ icon: 'Settings2', title: 'Forming-ready flatness', description: 'Steel finished and processed for consistent bending and forming on ducting lines.' }, { icon: 'TrendingUp', title: 'Consistent gauge control', description: 'Tight thickness tolerances that keep duct and casing dimensions accurate across runs.' }, { icon: 'Globe', title: 'Reliable production supply', description: 'Scheduled deliveries that keep ducting and casing lines running without material gaps.' }] },
    video: { label: 'IN MOTION', title: 'Steel That Keeps the Air Moving', description: 'See how processed CR and HR steel supports HVAC ducting and casing production.', videoUrl: 'https://cdn.pixabay.com/video/2020/10/30/54050-476694600_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Support built around your ducting and casing production line.', items: [{ title: 'Cut-to-Length & Slitting', description: 'Coil slit and sheet cut to your ducting and casing dimensions, ready for the production line.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Grade & Gauge Consultation', description: 'Guidance on CR/HR grade and thickness suited to ducting, casings, and structural HVAC components.', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Scheduled Bulk Delivery', description: 'Recurring delivery aligned to your production schedule.', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    faqs: { title: 'FAQs', items: [{ question: 'Do you supply both CR and HR steel for HVAC components?', answer: 'Yes, we supply both — CR for ducting and casings requiring a clean finish, HR for structural and heavier-gauge components.' }, { question: 'Can you process coil to our ducting dimensions?', answer: 'Yes, our processing facility slits and cuts to length according to your specification.' }, { question: 'What gauge range do you typically supply?', answer: 'We supply across the standard gauge range used in ducting and casing fabrication — share your specification for confirmation.' }, { question: 'How quickly can you dispatch standard orders?', answer: 'Standard grades held in stock typically dispatch within 48 hours.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get consistent, forming-ready steel for your HVAC production line.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const RENEWABLE_SOLAR: IndustryContent = {
    hero: { label: 'Renewable & Solar Industry', title: 'Structural Steel for Solar & Renewable Infrastructure', description: 'We supply HR steel plates, sheets, and structural sections for solar mounting structures, wind infrastructure, and renewable energy installations.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Steel Supporting a Cleaner Grid', description: 'Solar mounting structures and renewable energy infrastructure demand corrosion-resistant, structurally sound steel. We supply HR steel matched to your structural and durability requirements.' },
    stats: { label: 'Impact', title: 'Structural Supply at Project Scale', description: 'Supporting solar and renewable infrastructure projects across Northern India.', items: [{ value: 9, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 12, suffix: '+', label: 'Renewable projects supported' }, { value: 60, suffix: '+', label: 'Cities reached' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for solar and renewable infrastructure projects.', items: [{ title: 'Structural HR Steel Supply', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Custom Cutting & Processing', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Project-Based Dispatch', image: 'https://images.unsplash.com/photo-1504904126298-3fde501c9b31?w=800&q=80', href: '/project-based-steel' }, { title: 'Technical Grade Selection', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Structural steel sized and scheduled for utility and commercial-scale renewable projects.', points: [{ icon: 'ShieldCheck', title: 'Corrosion-aware grade selection', description: 'Guidance on grade and coating compatibility for outdoor solar and renewable installations.' }, { icon: 'TrendingUp', title: 'Project-scale capacity', description: 'Bulk structural steel supply sized to utility and commercial-scale renewable projects.' }, { icon: 'Globe', title: 'Site-aligned delivery', description: 'Delivery scheduled against your installation timeline and site logistics.' }] },
    video: { label: 'IN MOTION', title: 'Building the Backbone of Solar Farms', description: 'See how structural HR steel supports large-scale solar mounting installations.', videoUrl: 'https://cdn.pixabay.com/video/2016/09/21/5412-183416045_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Structural supply support for solar mounting structures and renewable infrastructure.', items: [{ title: 'Structural Plate & Sheet Supply', description: 'HR steel plates and sheets sized for solar mounting structures and renewable infrastructure.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Custom Processing for Structures', description: 'Cutting and processing to your mounting structure and framework specifications.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Project-Based Delivery', description: 'Dispatch scheduled against your installation phases and site access windows.', image: 'https://images.unsplash.com/photo-1504904126298-3fde501c9b31?w=800&q=80', href: '/project-based-steel' }] },
    faqs: { title: 'FAQs', items: [{ question: 'What steel grades suit solar mounting structures?', answer: 'IS 2062 Hot Rolled structural grades, typically E250 or higher depending on load requirements, are commonly used for mounting frames and structures.' }, { question: 'Can you supply steel for a phased installation project?', answer: 'Yes, our project-based supply approach schedules delivery against your installation phases rather than a single bulk dispatch.' }, { question: 'Do you provide plates and sections for large-scale projects?', answer: 'Yes, we supply HR plates, sheets, and structural sections sized to utility and commercial-scale renewable projects.' }, { question: 'What lead time should we plan for large orders?', answer: 'Lead time depends on volume and grade; our team will confirm a delivery schedule aligned to your project timeline during quoting.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get structural steel supply aligned to your solar or renewable energy project timeline.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const WAREHOUSING_LOGISTICS: IndustryContent = {
    hero: { label: 'Warehousing & Logistics Industry', title: 'Steel for Racking, Storage & Logistics Infrastructure', description: 'We supply CR and HR steel for storage racking, shelving systems, containers, and logistics infrastructure manufacturing.', image: 'https://images.unsplash.com/photo-1494412519320-aa613dfb7738?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Steel Behind Storage & Movement', description: 'Racking and storage system manufacturers need consistent-gauge steel that forms and welds reliably at scale. We supply CR and HR steel matched to your racking and container specifications.' },
    stats: { label: 'Impact', title: 'Reliable Supply, High Volume', description: 'Supporting racking, storage, and logistics infrastructure manufacturers.', items: [{ value: 6, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 14, suffix: '+', label: 'Racking & storage manufacturers served' }, { value: 48, suffix: 'hr', label: 'Standard dispatch window' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for racking, storage, and logistics infrastructure manufacturers.', items: [{ title: 'Sheet & Coil Supply', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/steel-procurement' }, { title: 'Slitting & Cut-to-Length', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Bulk Scheduled Delivery', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }, { title: 'Grade Selection Support', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Load-rated, production-scale steel supply for racking and storage manufacturing.', points: [{ icon: 'Settings2', title: 'Load-rated gauge control', description: 'Consistent thickness tolerances that keep racking and shelving load ratings accurate.' }, { icon: 'TrendingUp', title: 'Production-scale supply', description: 'Bulk CR and HR steel supply sized to high-volume racking and storage manufacturing.' }, { icon: 'Globe', title: 'Warehouse-to-warehouse reliability', description: 'Scheduled delivery from our own distribution network to your production facility.' }] },
    video: { label: 'IN MOTION', title: 'Steel That Stacks Up', description: 'See how processed steel supports high-volume racking and storage system manufacturing.', videoUrl: 'https://cdn.pixabay.com/video/2021/01/24/62900-504780516_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Support built around your racking and storage production volume.', items: [{ title: 'Slitting & Cut-to-Length', description: 'Coil slit and sheet cut to your racking and shelving component dimensions.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Grade & Gauge Consultation', description: 'Guidance on CR/HR grade and thickness suited to load-bearing racking components.', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Scheduled Bulk Delivery', description: 'Recurring delivery aligned to your production volume and schedule.', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    faqs: { title: 'FAQs', items: [{ question: 'What steel grades suit racking and shelving manufacturing?', answer: 'Both CR and HR grades are used depending on the component — CR for lighter shelving panels, HR for load-bearing frames and uprights.' }, { question: 'Can you process coil to our racking component dimensions?', answer: 'Yes, our processing facility slits and cuts to length according to your specification.' }, { question: 'Do you support recurring bulk orders?', answer: 'Yes, we structure recurring delivery schedules that match your production volume and reduce on-site inventory.' }, { question: 'What is your standard dispatch window?', answer: 'Standard grades held in stock typically dispatch within 48 hours; bulk or custom orders are scheduled around your production calendar.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get consistent steel supply for your racking, storage, or logistics infrastructure production.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const RAILWAY_TRANSPORTATION: IndustryContent = {
    hero: { label: 'Railway Transportation Industry', title: 'Certified Steel for Rail & Rolling Stock Manufacturing', description: 'We supply certified HR and CR steel plates, sheets, and coils for railway wagons, coaches, and rolling stock component manufacturing.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Steel on Track for Reliability', description: 'Railway and rolling stock manufacturers require certified, traceable steel that meets stringent structural and safety standards. We supply grade-matched HR and CR steel with full documentation.' },
    stats: { label: 'Impact', title: 'Certified for Safety-Critical Work', description: 'Supporting rolling stock manufacturers with fully traceable structural steel.', items: [{ value: 10, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 9, suffix: '+', label: 'Rolling stock manufacturers served' }, { value: 100, suffix: '%', label: 'Batches with test certificates' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for railway and rolling stock manufacturers.', items: [{ title: 'Certified Plate & Sheet Supply', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Custom Cutting & Processing', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Technical Grade Matching', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Project-Based Dispatch', image: 'https://images.unsplash.com/photo-1504904126298-3fde501c9b31?w=800&q=80', href: '/project-based-steel' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Certified, traceable structural steel for safety-critical rail applications.', points: [{ icon: 'ShieldCheck', title: 'Full traceability', description: 'Every batch backed by a Manufacturer Test Certificate, essential for safety-critical rail applications.' }, { icon: 'Settings2', title: 'Precision processing', description: 'Plates and sheets cut and processed to rolling stock component specifications.' }, { icon: 'TrendingUp', title: 'Project-scale reliability', description: 'Bulk supply capacity sized to wagon and coach manufacturing production runs.' }] },
    video: { label: 'IN MOTION', title: 'Steel That Moves Millions', description: 'See how certified structural steel supports railway wagon and coach manufacturing.', videoUrl: 'https://cdn.pixabay.com/video/2018/11/02/19084-297771746_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Certified structural supply for rolling stock and rail infrastructure manufacturing.', items: [{ title: 'Certified Structural Supply', description: 'HR plates and sheets with full Manufacturer Test Certificate documentation for safety-critical rail components.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Custom Processing for Rolling Stock', description: 'Cutting and processing to wagon, coach, and rolling stock component specifications.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Project-Based Delivery', description: 'Delivery scheduled against your manufacturing phases and production calendar.', image: 'https://images.unsplash.com/photo-1504904126298-3fde501c9b31?w=800&q=80', href: '/project-based-steel' }] },
    faqs: { title: 'FAQs', items: [{ question: 'Do you provide test certificates for railway-grade steel?', answer: 'Yes, every batch is sourced directly from SAIL and comes with a full Manufacturer Test Certificate for complete traceability.' }, { question: 'What grades are typically used for rolling stock manufacturing?', answer: 'IS 2062 structural HR grades are common for frames and structural components; specific grade requirements vary by application and are confirmed during technical review.' }, { question: 'Can you support phased delivery for a wagon or coach production run?', answer: 'Yes, our project-based supply approach schedules delivery against your production phases.' }, { question: 'What is the typical lead time for bulk structural orders?', answer: 'Lead time depends on volume and grade; our team confirms a delivery schedule aligned to your production calendar during quoting.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get certified, traceable steel supply for your railway or rolling stock manufacturing.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const INDUSTRIAL_FABRICATION: IndustryContent = {
    hero: { label: 'Industrial Fabrication Industry', title: 'Dependable Steel for Industrial Fabrication Workshops', description: 'We supply CR and HR steel plates, sheets, and coils to fabrication workshops building structural frames, equipment skids, and custom industrial assemblies.', image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Raw Material for Every Build', description: "Fabrication workshops need steel that's available when the job requires it, in the grade and size the drawing calls for. We supply CR and HR steel matched to your fabrication schedule." },
    stats: { label: 'Impact', title: 'Ready When You Are', description: 'Supporting fabrication workshops with dependable steel supply.', items: [{ value: 8, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 25, suffix: '+', label: 'Fabrication workshops served' }, { value: 48, suffix: 'hr', label: 'Standard dispatch window' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for industrial fabrication workshops.', items: [{ title: 'Plate, Sheet & Coil Supply', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Cutting & Shearing Services', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Technical Grade Support', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Ready Stock Availability', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/ready-stock-supply' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Job-ready steel processing backed by ready stock availability.', points: [{ icon: 'Settings2', title: 'Job-ready cutting', description: 'Plates and sheets sheared and cut to your fabrication drawing dimensions.' }, { icon: 'TrendingUp', title: 'Ready stock access', description: 'Common grades and sizes held in stock for fast-turnaround fabrication jobs.' }, { icon: 'Globe', title: 'Workshop-scale reliability', description: 'Supply structured for both one-off jobs and recurring fabrication workshop demand.' }] },
    video: { label: 'IN MOTION', title: 'From Stock to Structure', description: 'See how ready-stock steel supports fast-turnaround industrial fabrication work.', videoUrl: 'https://cdn.pixabay.com/video/2022/10/25/136365-764353842_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Support built for fabrication workshops, from ready stock to custom cutting.', items: [{ title: 'Cutting & Shearing', description: 'Plates and sheets processed to your fabrication drawing dimensions before dispatch.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Ready Stock Supply', description: 'Common CR and HR grades and sizes held in stock for fast-turnaround jobs.', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/ready-stock-supply' }, { title: 'Technical Grade Support', description: 'Guidance on grade selection for structural, load-bearing, and general fabrication work.', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }] },
    faqs: { title: 'FAQs', items: [{ question: 'Do you hold ready stock for common fabrication jobs?', answer: 'Yes, we maintain ready stock of common CR and HR grades and sizes for fast-turnaround fabrication work.' }, { question: 'Can you cut plate to our fabrication drawing dimensions?', answer: 'Yes, our processing facility shears and cuts plates and sheets to your specified dimensions.' }, { question: 'Do you supply both one-off and recurring fabrication workshops?', answer: 'Yes, we support both single-job orders and recurring supply arrangements for regular fabrication workshop demand.' }, { question: 'What grades are best for general structural fabrication?', answer: 'IS 2062 E250 is the most common general-purpose structural grade; higher grades are available for weight-sensitive applications.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get dependable steel supply for your fabrication workshop, from one-off jobs to recurring orders.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const OEM_MANUFACTURING: IndustryContent = {
    hero: { label: 'OEM Manufacturing Industry', title: 'Consistent Steel Supply for OEM Production Lines', description: 'We supply CR and HR steel matched to OEM production specifications, with certified quality and delivery scheduled around your manufacturing calendar.', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Built Around Your Production Line', description: "OEM manufacturers need steel that arrives on schedule, in the exact grade and gauge their production line depends on. We structure supply around your manufacturing calendar, not the other way around." },
    stats: { label: 'Impact', title: 'On Schedule, Every Time', description: 'Supporting OEM manufacturers with reliable, scheduled steel supply.', items: [{ value: 9, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 20, suffix: '+', label: 'OEM partners served' }, { value: 99, suffix: '%', label: 'On-time delivery rate' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for OEM manufacturers.', items: [{ title: 'Certified Sheet & Coil Supply', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/steel-procurement' }, { title: 'Custom Slitting & Cutting', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Technical Grade Matching', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Annual Contract Options', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/annual-supply-contract' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Certified steel processed and scheduled around your OEM production line.', points: [{ icon: 'Settings2', title: 'Production-matched processing', description: 'Steel slit and cut to your exact OEM production line specifications.' }, { icon: 'TrendingUp', title: 'Scheduled reliability', description: 'Delivery scheduled against your production calendar to avoid line stoppages.' }, { icon: 'ShieldCheck', title: 'Certified quality', description: 'Every batch traceable to SAIL with full Manufacturer Test Certificate documentation.' }] },
    video: { label: 'IN MOTION', title: 'Precision Supply for Precision Production', description: 'See how scheduled, grade-matched steel supply supports OEM manufacturing lines.', videoUrl: 'https://cdn.pixabay.com/video/2020/10/30/54050-476694600_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Supply structured around your OEM production calendar.', items: [{ title: 'Custom Slitting & Cutting', description: "Coil and sheet processed to your OEM production line's exact dimensional requirements.", image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Scheduled Production Supply', description: 'Delivery structured around your manufacturing calendar to keep production lines running.', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }, { title: 'Annual Supply Contracts', description: 'Locked-in pricing and guaranteed volume for predictable OEM production planning.', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80', href: '/annual-supply-contract' }] },
    faqs: { title: 'FAQs', items: [{ question: 'Can you structure delivery around our production schedule?', answer: 'Yes, we schedule deliveries to match your manufacturing calendar rather than standard freight windows.' }, { question: 'Do you offer annual supply contracts for OEM manufacturers?', answer: 'Yes, our Annual Supply Contract solution locks in pricing and guarantees volume for predictable yearly planning.' }, { question: 'What grades are commonly supplied to OEM manufacturers?', answer: 'This varies by product; our technical team matches CR or HR grade and gauge to your specific component and forming requirements.' }, { question: 'Can you support just-in-time delivery for our line?', answer: "Yes, we coordinate delivery scheduling to align with your production line's cadence and minimize on-site inventory." }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get steel supply structured around your OEM production schedule, not standard freight windows.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const UTENSILS: IndustryContent = {
    hero: { label: 'Utensils & Kitchenware Industry', title: 'Clean-Finish CR Steel for Utensil Manufacturing', description: 'We supply Cold Rolled steel sheets and coils suited to utensil and kitchenware manufacturing, offering the clean surface finish and formability deep-drawing requires.', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Steel Behind Everyday Essentials', description: 'Utensil manufacturing depends on deep-drawing-grade CR steel with a clean, defect-free surface. We supply EDD and DD grade CR steel matched to your forming process.' },
    stats: { label: 'Impact', title: 'Formed Without Compromise', description: 'Supporting utensil and kitchenware manufacturers with deep-drawing-grade CR steel.', items: [{ value: 4, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 12, suffix: '+', label: 'Utensil manufacturers served' }, { value: 72, suffix: 'hr', label: 'Standard dispatch window' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for utensil and kitchenware manufacturers.', items: [{ title: 'Deep-Drawing Grade CR Supply', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/steel-procurement' }, { title: 'Slitting & Cut-to-Size', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Surface Finish Selection', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Scheduled Bulk Delivery', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Deep-drawing-grade CR steel with a clean, consistent finish.', points: [{ icon: 'Settings2', title: 'Deep-drawing formability', description: 'EDD and DD grade CR steel selected for consistent deep-drawing performance without cracking or tearing.' }, { icon: 'ShieldCheck', title: 'Clean surface finish', description: 'Skin-passed CR steel with a defect-free surface suited to polishing and finishing processes.' }, { icon: 'TrendingUp', title: 'Consistent batch quality', description: 'Steel quality that stays consistent batch to batch, reducing forming rejects on high-volume lines.' }] },
    video: { label: 'IN MOTION', title: 'From Coil to Kitchen', description: 'See how deep-drawing-grade CR steel becomes everyday utensils and kitchenware.', videoUrl: 'https://cdn.pixabay.com/video/2016/09/21/5412-183416045_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Support built around your utensil forming line, from grade to scheduled delivery.', items: [{ title: 'Deep-Drawing Grade Supply', description: 'EDD and DD grade CR steel selected for consistent forming performance on utensil production lines.', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/steel-procurement' }, { title: 'Slitting & Cut-to-Size', description: 'Coil slit and sheet cut to your utensil blank dimensions before dispatch.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Scheduled Bulk Delivery', description: 'Recurring delivery aligned to your production volume and schedule.', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    faqs: { title: 'FAQs', items: [{ question: 'What CR grade is used for utensil manufacturing?', answer: 'Extra Deep Drawing (EDD) or Deep Drawing (DD) grade CR steel under IS 513 is typically used, depending on the depth and complexity of the drawn shape.' }, { question: 'Can you supply pre-slit blanks for our press line?', answer: 'Yes, our processing facility slits and cuts coil to your specified blank dimensions.' }, { question: 'Does the surface finish support polishing?', answer: 'Yes, our skin-passed CR steel provides a clean, defect-free surface suited to subsequent polishing and finishing.' }, { question: 'What is your standard order lead time?', answer: 'Standard grades held in stock typically dispatch within 2-3 days; bulk orders are scheduled around your production calendar.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get consistent, deep-drawing-grade CR steel for your utensil production line.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const WORKING_MACHINERY: IndustryContent = {
    hero: { label: 'Working Machinery Industry', title: 'Heavy-Duty Steel for Working Machinery Manufacturing', description: 'We supply HR steel plates and sheets for construction, agricultural, and industrial working machinery, including frames, chassis, and structural components.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Steel Built for Heavy Work', description: "Working machinery manufacturers need steel that holds up to structural load and repeated stress. We supply HR plates and sheets matched to your machinery's structural requirements." },
    stats: { label: 'Impact', title: 'Structural Reliability, Proven', description: 'Supporting construction, agricultural, and industrial machinery manufacturers.', items: [{ value: 11, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 15, suffix: '+', label: 'Machinery manufacturers served' }, { value: 48, suffix: 'hr', label: 'Standard dispatch window' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for working machinery manufacturers.', items: [{ title: 'Structural Plate & Sheet Supply', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Cutting & Shearing Services', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Technical Grade Matching', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Ready Stock Availability', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/ready-stock-supply' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Structural-grade steel processed for heavy machinery frames and chassis.', points: [{ icon: 'Settings2', title: 'Structural-grade steel', description: 'HR plates and sheets in structural grades suited to machinery frames and chassis.' }, { icon: 'TrendingUp', title: 'Heavy-duty processing', description: 'Plate cutting and shearing sized for heavy machinery component dimensions.' }, { icon: 'Globe', title: 'Reliable production supply', description: 'Bulk and recurring supply structured around your machinery production schedule.' }] },
    video: { label: 'IN MOTION', title: 'Steel Behind the Machines That Build', description: 'See how structural HR steel supports construction and industrial machinery manufacturing.', videoUrl: 'https://cdn.pixabay.com/video/2021/01/24/62900-504780516_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Structural supply support for working machinery manufacturers.', items: [{ title: 'Structural Plate Supply', description: 'HR plates and sheets in structural grades sized for machinery frames, chassis, and load-bearing components.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Cutting & Shearing', description: 'Plate and sheet processed to your machinery component drawing dimensions.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Ready Stock Supply', description: 'Common structural grades and sizes held in stock for fast-turnaround machinery production.', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/ready-stock-supply' }] },
    faqs: { title: 'FAQs', items: [{ question: 'What steel grades suit working machinery manufacturing?', answer: 'IS 2062 structural HR grades, typically E250 to E410 depending on load requirements, are commonly used for frames and structural components.' }, { question: 'Can you cut plate to our machinery component dimensions?', answer: 'Yes, our processing facility shears and cuts to your specified dimensions.' }, { question: 'Do you hold ready stock for common machinery grades?', answer: 'Yes, we maintain ready stock of common structural grades and sizes for fast-turnaround production.' }, { question: 'What is the typical lead time for bulk structural orders?', answer: 'Standard grades held in stock typically dispatch within 48 hours; bulk or custom orders are scheduled around your production calendar.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get heavy-duty structural steel supply for your working machinery production line.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const STEEL_DRUMS: IndustryContent = {
    hero: { label: 'Steel Drums Industry', title: 'Consistent CR Steel for Drum & Barrel Manufacturing', description: 'We supply Cold Rolled steel sheets and coils for steel drum and barrel manufacturing, offering the gauge consistency and formability drum rolling and seaming require.', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Steel Rolled Into Reliable Containers', description: 'Drum manufacturing depends on consistent-gauge CR steel that rolls and seams cleanly at high volume. We supply steel matched to your drum rolling and welding line.' },
    stats: { label: 'Impact', title: 'Consistent Gauge, High Volume', description: 'Supporting drum and barrel manufacturers with reliable CR steel supply.', items: [{ value: 5, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 10, suffix: '+', label: 'Drum manufacturers served' }, { value: 72, suffix: 'hr', label: 'Standard dispatch window' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for drum and barrel manufacturers.', items: [{ title: 'CR Sheet & Coil Supply', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/steel-procurement' }, { title: 'Slitting & Cut-to-Size', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Grade & Gauge Selection', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Scheduled Bulk Delivery', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Rolling-line-ready CR steel sized for high-volume drum manufacturing.', points: [{ icon: 'Settings2', title: 'Rolling-line-ready gauge', description: 'Consistent thickness tolerances suited to high-speed drum rolling and seaming lines.' }, { icon: 'TrendingUp', title: 'High-volume supply capacity', description: 'Bulk CR steel supply sized to continuous drum manufacturing production.' }, { icon: 'ShieldCheck', title: 'Weld-consistent quality', description: 'Steel quality that stays consistent batch to batch, supporting reliable seam welding.' }] },
    video: { label: 'IN MOTION', title: 'From Coil to Container', description: 'See how consistent-gauge CR steel supports high-volume drum and barrel manufacturing.', videoUrl: 'https://cdn.pixabay.com/video/2018/11/02/19084-297771746_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Support built around your drum rolling and seaming line.', items: [{ title: 'Slitting & Cut-to-Size', description: 'Coil slit and sheet cut to your drum blank dimensions before dispatch.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Grade & Gauge Consultation', description: 'Guidance on CR grade and thickness suited to drum rolling and seam welding.', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Scheduled Bulk Delivery', description: 'Recurring delivery aligned to your production volume and schedule.', image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80', href: '/supply-chain' }] },
    faqs: { title: 'FAQs', items: [{ question: 'What CR grade is typically used for steel drum manufacturing?', answer: 'Commercial (D) grade CR steel under IS 513 is commonly used, with tighter gauge tolerance specified for consistent rolling and seaming.' }, { question: 'Can you supply pre-slit coil for our drum line?', answer: 'Yes, our processing facility slits coil to your specified width for direct line feeding.' }, { question: 'Do you support high-volume recurring orders?', answer: 'Yes, we structure recurring delivery schedules sized to continuous drum manufacturing production.' }, { question: 'What is your standard dispatch window?', answer: 'Standard grades held in stock typically dispatch within 2-3 days; bulk orders are scheduled around your production calendar.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get consistent-gauge CR steel supply for your drum or barrel production line.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const METRO: IndustryContent = {
    hero: { label: 'Metro Rail Industry', title: 'Certified Steel for Metro Rail Infrastructure', description: 'We supply certified HR steel plates and structural sections for metro rail infrastructure, including viaducts, station structures, and rolling stock components.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1200&q=80' },
    mission: { label: 'Mission', title: 'Steel Moving Urban India', description: 'Metro rail projects demand certified structural steel with full traceability and strict quality compliance. We supply grade-matched HR steel backed by complete documentation for urban rail infrastructure.' },
    stats: { label: 'Impact', title: 'Built for Compliance and Scale', description: 'Supporting metro rail infrastructure projects with certified structural steel.', items: [{ value: 12, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 6, suffix: '+', label: 'Metro infrastructure projects supported' }, { value: 100, suffix: '%', label: 'Batches with test certificates' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for metro rail infrastructure projects.', items: [{ title: 'Certified Structural Plate Supply', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Project-Based Processing', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Technical Grade Matching', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Phased Project Dispatch', image: 'https://images.unsplash.com/photo-1504904126298-3fde501c9b31?w=800&q=80', href: '/project-based-steel' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Certified structural steel scheduled against your metro construction phases.', points: [{ icon: 'ShieldCheck', title: 'Full material traceability', description: 'Every batch backed by a Manufacturer Test Certificate, essential for infrastructure compliance and audits.' }, { icon: 'TrendingUp', title: 'Large-scale project capacity', description: 'Bulk structural steel supply sized to viaduct, station, and infrastructure-scale metro projects.' }, { icon: 'Settings2', title: 'Phase-aligned delivery', description: 'Delivery scheduled against your construction phases and site access windows.' }] },
    video: { label: 'IN MOTION', title: 'Steel Beneath the City', description: 'See how certified structural steel supports metro rail viaduct and station construction.', videoUrl: 'https://cdn.pixabay.com/video/2022/10/25/136365-764353842_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Certified structural supply for metro rail infrastructure projects.', items: [{ title: 'Certified Structural Supply', description: 'HR plates and structural sections with full Manufacturer Test Certificate documentation for infrastructure compliance.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Project-Based Processing', description: 'Cutting and processing to viaduct, station, and structural component specifications.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Phased Project Delivery', description: 'Delivery scheduled against your construction phases and site logistics.', image: 'https://images.unsplash.com/photo-1504904126298-3fde501c9b31?w=800&q=80', href: '/project-based-steel' }] },
    faqs: { title: 'FAQs', items: [{ question: 'Do you provide full documentation for infrastructure compliance audits?', answer: 'Yes, every batch is sourced directly from SAIL and comes with a complete Manufacturer Test Certificate for full traceability.' }, { question: 'Can you support phased delivery across a multi-year metro project?', answer: 'Yes, our project-based supply approach schedules delivery against your construction phases rather than a single bulk dispatch.' }, { question: 'What structural grades are used in metro infrastructure?', answer: 'IS 2062 structural HR grades, typically E250 and above, are used depending on load and application; exact grades are confirmed during technical review.' }, { question: 'What lead time should we plan for large infrastructure orders?', answer: 'Lead time depends on volume, grade, and phasing; our team confirms a delivery schedule aligned to your project timeline during quoting.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get certified structural steel supply for your metro rail infrastructure project.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

const TUNNEL: IndustryContent = {
    hero: { label: 'Tunnel Construction Industry', title: 'Structural Steel for Tunnel Construction & Lining', description: 'We supply HR steel plates and structural sections for tunnel boring, lining, and underground infrastructure construction projects.', image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200&q=80' },
    mission: { label: 'Mission', title: "Steel Supporting What's Built Below", description: 'Tunnel construction demands structural steel that performs reliably under high load and confined-space installation conditions. We supply certified HR steel matched to your tunnel lining and support structure specifications.' },
    stats: { label: 'Impact', title: 'Certified for Underground Infrastructure', description: 'Supporting tunnel construction and lining projects with certified structural steel.', items: [{ value: 10, suffix: 'k+', label: 'Tons supplied yearly' }, { value: 5, suffix: '+', label: 'Tunnel infrastructure projects supported' }, { value: 100, suffix: '%', label: 'Batches with test certificates' }] },
    howHelp: { title: 'HOW WE CAN HELP', subtitle: 'A selection of our services for tunnel construction projects.', items: [{ title: 'Certified Structural Plate Supply', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Project-Based Processing', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Technical Grade Matching', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/technical-steel-selection' }, { title: 'Phased Project Dispatch', image: 'https://images.unsplash.com/photo-1504904126298-3fde501c9b31?w=800&q=80', href: '/project-based-steel' }] },
    builtToDeliver: { title: 'BUILT TO DELIVER', subtitle: 'Certified structural steel scheduled against your excavation and construction phases.', points: [{ icon: 'ShieldCheck', title: 'Full material traceability', description: 'Every batch backed by a Manufacturer Test Certificate, critical for underground infrastructure compliance.' }, { icon: 'TrendingUp', title: 'Heavy structural capacity', description: 'Bulk HR plate and section supply sized to tunnel lining and support structure requirements.' }, { icon: 'Settings2', title: 'Phase-aligned delivery', description: 'Delivery scheduled against your excavation and construction phases.' }] },
    video: { label: 'IN MOTION', title: 'Steel Supporting the Underground', description: 'See how structural HR steel supports tunnel lining and underground construction.', videoUrl: 'https://cdn.pixabay.com/video/2020/10/30/54050-476694600_large.mp4' },
    services: { title: 'OUR SERVICES', subtitle: 'Certified structural supply for tunnel construction and lining projects.', items: [{ title: 'Certified Structural Supply', description: 'HR plates and structural sections with full Manufacturer Test Certificate documentation for underground infrastructure compliance.', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/steel-procurement' }, { title: 'Project-Based Processing', description: 'Cutting and processing to tunnel lining and support structure specifications.', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/custom-steel-processing' }, { title: 'Phased Project Delivery', description: 'Delivery scheduled against your excavation and construction phases.', image: 'https://images.unsplash.com/photo-1504904126298-3fde501c9b31?w=800&q=80', href: '/project-based-steel' }] },
    faqs: { title: 'FAQs', items: [{ question: 'Do you provide certified steel suitable for underground infrastructure?', answer: 'Yes, every batch is sourced directly from SAIL and comes with a complete Manufacturer Test Certificate for full traceability.' }, { question: 'Can you support phased delivery across a multi-stage tunnel project?', answer: 'Yes, our project-based supply approach schedules delivery against your excavation and construction phases.' }, { question: 'What structural grades are used for tunnel lining and supports?', answer: 'IS 2062 structural HR grades are used depending on load and application; exact grades are confirmed during technical review.' }, { question: 'What lead time should we plan for large infrastructure orders?', answer: 'Lead time depends on volume, grade, and phasing; our team confirms a delivery schedule aligned to your project timeline during quoting.' }] },
    cta: { title: 'TALK TO AN EXPERT', description: 'Get certified structural steel supply for your tunnel construction project.', btnText: 'Contact Us', btnHref: '/contact-us', bgImage: CTA_BG },
};

export const NEW_INDUSTRIES_PAGES = [
    buildIndustryPage('auto-components', 'Auto Components', AUTO_COMPONENTS),
    buildIndustryPage('electrical-panel', 'Electrical Panel', ELECTRICAL_PANEL),
    buildIndustryPage('furniture', 'Furniture', FURNITURE),
    buildIndustryPage('hvac', 'HVAC', HVAC),
    buildIndustryPage('renewable-solar', 'Renewable & Solar', RENEWABLE_SOLAR),
    buildIndustryPage('warehousing-logistics', 'Warehousing & Logistics', WAREHOUSING_LOGISTICS),
    buildIndustryPage('railway-transportation', 'Railway Transportation', RAILWAY_TRANSPORTATION),
    buildIndustryPage('industrial-fabrication', 'Industrial Fabrication', INDUSTRIAL_FABRICATION),
    buildIndustryPage('oem-manufacturing', 'OEM Manufacturing', OEM_MANUFACTURING),
    buildIndustryPage('utensils', 'Utensils', UTENSILS),
    buildIndustryPage('working-machinery', 'Working Machinery', WORKING_MACHINERY),
    buildIndustryPage('steel-drums', 'Steel Drums', STEEL_DRUMS),
    buildIndustryPage('metro', 'Metro', METRO),
    buildIndustryPage('tunnel', 'Tunnel', TUNNEL),
];

export const NAVBAR_INDUSTRIES_LINKS = [
    { label: 'Auto Components', href: '/industries/auto-components' },
    { label: 'Electrical Panel', href: '/industries/electrical-panel' },
    { label: 'Furniture', href: '/industries/furniture' },
    { label: 'HVAC', href: '/industries/hvac' },
    { label: 'Renewable & Solar', href: '/industries/renewable-solar' },
    { label: 'Warehousing & Logistics', href: '/industries/warehousing-logistics' },
    { label: 'Railway Transportation', href: '/industries/railway-transportation' },
    { label: 'Industrial Fabrication', href: '/industries/industrial-fabrication' },
    { label: 'OEM Manufacturing', href: '/industries/oem-manufacturing' },
    { label: 'Utensils', href: '/industries/utensils' },
    { label: 'Working Machinery', href: '/industries/working-machinery' },
    { label: 'Steel Drums', href: '/industries/steel-drums' },
    { label: 'Metro', href: '/industries/metro' },
    { label: 'Tunnel', href: '/industries/tunnel' },
];
