// Seed data for the 5 additional Services pages: Coil Slitting,
// Cut-To-Length Service, Luster Steel Processing, Bulk Industrial Supply,
// Delivery & Logistics Service. Companion to seedData.ts / newSolutionsData.ts
// — kept separate since it was requested and shipped as its own batch.
import type { SeedPage } from './seedData';

const SERVICES_DATA_7 = [
  { title: "Coil Slitting", description: "High-speed, precision slitting that converts master coils into narrower, tightly toleranced slit coils.", image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80", href: "/services/coil-slitting" },
  { title: "Cut-To-Length Service", description: "Master coils converted into flat, perfectly squared sheets and blanks, cut to your exact length.", image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80", href: "/services/cut-to-length" },
  { title: "Luster Steel Processing", description: "Surface finishing treatments delivering a clean, bright luster finish for appearance-critical applications.", image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80", href: "/services/luster-steel-processing" },
  { title: "Bulk Industrial Supply", description: "High-tonnage flat steel supply handled as a single, coordinated dispatch for large-volume requirements.", image: "https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80", href: "/services/bulk-industrial-supply" },
  { title: "Delivery & Logistics Service", description: "Fleet coordination, route planning, and handling protocols that move your steel from warehouse to gate.", image: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80", href: "/services/logistics-delivery" },
  { title: "Regional Distribution Network", description: "Our Delhi warehouse and rail-and-road distribution network reach 10+ states across Northern India.", image: "https://images.unsplash.com/photo-1597334948330-38795f25d05d?q=80&w=1171", href: "/services/port-network" },
  { title: "Warehousing & Distribution", description: "Secure, high-capacity warehousing and coordinated dispatch connecting SAIL's plants to your site.", image: "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=800&q=80", href: "/services/port-services" },
];

export const NEW_SERVICES_PAGES: SeedPage[] = [
  {
    slug: 'services-coil-slitting', title: 'Services — Coil Slitting', status: 'published',
    seo: {
      metaTitle: 'Coil Slitting Services India | Sonatek Steels',
      metaDescription: 'Precision CR & HR coil slitting services from Sonatek Steels — custom-width steel coils, reduced material wastage, and reliable industrial coil slitting supply across India.',
      ogImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=85',
    },
    blocks: [
      { blockType: 'service-hero', order: 0, anchorId: 'overview', data: {
        title: 'Precision Slitting. Maximum Material Utilization. Better Manufacturing Efficiency.',
        breadcrumbLabel: 'Coil Slitting',
        description: "Manufacturers require steel that fits their production process, not the other way around. Our coil slitting service transforms wide Cold Rolled (CR) and Hot Rolled (HR) steel coils into multiple narrower coils with precision, helping manufacturers reduce material wastage, improve production efficiency, and optimize operational costs — whether you're producing automotive components, electrical panels, tube mills, roll-formed sections, or industrial equipment.",
        image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&q=85',
        ctaText: 'Request a Slitting Quote', ctaHref: '/contact-us',
        secondaryCtaText: 'Speak with a Processing Expert', secondaryCtaHref: '/contact-us',
      } },
      { blockType: 'mission-section', order: 1, anchorId: 'what-is-coil-slitting', data: {
        label: 'OVERVIEW', title: 'What is Coil Slitting?',
        bodyText: 'Coil slitting is a precision steel processing method where a master coil is longitudinally cut into multiple narrower coils while maintaining consistent width, edge quality, and material integrity. Instead of purchasing a standard-width steel coil and processing it internally, manufacturers receive slit coils tailored to their exact production requirements — reducing additional handling, minimizing scrap, and enabling faster integration into manufacturing processes.',
      } },
      { blockType: 'process-steps', order: 2, anchorId: 'how-it-works', data: {
        label: 'PROCESS', title: 'How Coil Slitting Works',
        steps: [
          { title: 'Master Coil Selection', description: "The required Cold Rolled (CR) or Hot Rolled (HR) master coil is selected based on the customer's specifications." },
          { title: 'Precision Slitting', description: 'The coil passes through a slitting line where precision circular knives divide it into multiple narrower coils.' },
          { title: 'Edge & Width Inspection', description: 'Each slit coil is checked to ensure consistent width, edge quality, and dimensional accuracy.' },
          { title: 'Recoiling & Packaging', description: 'Each strip is recoiled separately, securely packed, and prepared for dispatch.' },
          { title: 'Delivery', description: 'The processed coils are delivered to your manufacturing facility, ready for production.' },
        ],
      } },
      { blockType: 'icon-grid', order: 3, anchorId: 'benefits', data: {
        title: 'WHY CHOOSE COIL SLITTING?',
        subtitle: 'Many manufacturers purchase wide coils but only require narrower widths for production. Without slitting, they often need additional processing equipment, labour, and time — our slitting solutions help eliminate these challenges.',
        items: [
          { icon: 'Ruler', title: 'Precision Width Customization', description: 'Coils slit to the exact width your production line requires.' },
          { icon: 'Recycle', title: 'Reduced Material Wastage', description: 'Less scrap and offcuts compared to processing standard-width coil in-house.' },
          { icon: 'Zap', title: 'Faster Production Setup', description: 'Production-ready widths mean less setup and handling on your line.' },
          { icon: 'TrendingUp', title: 'Improved Manufacturing Efficiency', description: 'Fewer processing steps once material reaches your facility.' },
          { icon: 'DollarSign', title: 'Lower Processing Costs', description: 'Reduces the need for in-house slitting equipment and labour.' },
          { icon: 'Boxes', title: 'Better Inventory Management', description: 'Stock exact widths instead of oversized master coils.' },
          { icon: 'Trash2', title: 'Reduced Scrap Generation', description: 'Precision cuts minimize offcut and trim loss.' },
          { icon: 'PackageCheck', title: 'Ready-to-Use Steel Coils', description: 'Coils arrive ready to feed directly into your process.' },
        ],
      } },
      { blockType: 'icon-grid', order: 4, anchorId: 'industries', data: {
        title: 'INDUSTRIES THAT BENEFIT FROM COIL SLITTING',
        subtitle: 'Our slitting services support a wide range of manufacturing industries, including:',
        items: [
          { icon: 'Car', title: 'Automotive Industry', description: 'Steel strips for body components, brackets, reinforcement parts, and automotive assemblies.' },
          { icon: 'PanelsTopLeft', title: 'Electrical Panel Manufacturing', description: 'Precision slit coils for electrical cabinets, switchgear, control panels, and enclosures.' },
          { icon: 'CircleDot', title: 'Tube & Pipe Manufacturing', description: 'Narrow coils designed for tube mills and pipe production with consistent width and edge quality.' },
          { icon: 'Layers', title: 'Roll Forming Industry', description: 'Steel strips for channels, profiles, sections, roofing components, and structural applications.' },
          { icon: 'Armchair', title: 'Furniture Manufacturing', description: 'Material for office furniture, storage systems, shelving, and modular furniture.' },
          { icon: 'Factory', title: 'Industrial Fabrication', description: 'Precision steel strips for fabricated assemblies, machine components, and engineering products.' },
        ],
      } },
      { blockType: 'how-we-can-help', order: 5, anchorId: 'applications', data: {
        label: 'APPLICATIONS', title: 'WHERE SLIT COILS ARE USED',
        subtitle: 'Slit coils from our lines feed directly into these production processes and end-use applications.',
        items: [
          { title: 'Automotive Components', image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80', href: '/industries/automotive' },
          { title: 'Electrical Equipment', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80', href: '/industries/electrical-panel' },
          { title: 'Industrial Cabinets', image: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=800&q=80', href: '/industries/industrial-fabrication' },
          { title: 'Tube Manufacturing', image: 'https://images.unsplash.com/photo-1693847173071-bd6237101335?q=80&w=1170', href: '/industries/oil-gas' },
          { title: 'Steel Furniture', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/industries/furniture' },
          { title: 'Storage Systems', image: 'https://images.unsplash.com/photo-1494412519320-aa613dfb7738?w=800&q=80', href: '/industries/warehousing-logistics' },
          { title: 'Engineering Components', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', href: '/industries/heavy-engineering' },
          { title: 'Machine Manufacturing', image: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=800&q=80', href: '/industries/working-machinery' },
          { title: 'Industrial Fabrication', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80', href: '/industries/industrial-fabrication' },
          { title: 'Roll Formed Products', image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1176', href: '/industries/construction' },
        ],
      } },
      { blockType: 'built-to-deliver', order: 6, anchorId: 'advantages', data: {
        label: 'WHY SONATEK STEELS', title: 'Why Manufacturers Choose Sonatek Steels',
        subtitle: 'We understand that manufacturing depends on precision, consistency, and timely supply. Our processing approach is designed to support production efficiency and reduce operational challenges.',
        points: [
          { icon: 'ShieldCheck', title: 'Premium CR & HR Steel', description: 'Sourced from certified primary producers for consistent quality.' },
          { icon: 'Ruler', title: 'Precision Processing', description: 'CNC-controlled slitting lines built to hold tight tolerances.' },
          { icon: 'Warehouse', title: 'Ready Inventory', description: 'Stocked master coils ready to process without long lead times.' },
          { icon: 'BadgeCheck', title: 'Reliable Supply', description: 'Consistent availability backed by a dependable procurement network.' },
          { icon: 'Truck', title: 'Fast Dispatch', description: 'Streamlined processing-to-dispatch turnaround.' },
          { icon: 'Briefcase', title: 'Industrial Procurement Expertise', description: 'Guidance from a team that understands industrial buying cycles.' },
          { icon: 'Headset', title: 'Dedicated Customer Support', description: 'A responsive team throughout your order and processing cycle.' },
          { icon: 'Globe', title: 'Pan-India Logistics', description: 'Coordinated dispatch and delivery across the country.' },
        ],
      } },
      { blockType: 'mission-section', order: 7, anchorId: 'quality', data: {
        label: 'QUALITY ASSURANCE', title: 'Quality You Can Depend On',
        bodyText: 'Every slit coil undergoes quality verification before dispatch to help ensure consistency and reliable performance in downstream manufacturing processes. Our focus is not only on supplying steel but on delivering processing solutions that improve productivity and reduce unnecessary manufacturing costs.',
      } },
      { blockType: 'icon-grid', order: 8, anchorId: 'precision', data: {
        title: 'WHY PRECISION MATTERS',
        subtitle: 'Even small variations in coil width can impact production efficiency, product quality, and machine performance. Precision slitting helps manufacturers:',
        items: [
          { icon: 'Ruler', title: 'Improve dimensional consistency', description: 'Every slit coil holds tight, repeatable width tolerances.' },
          { icon: 'Clock', title: 'Reduce production downtime', description: 'Fewer stoppages caused by inconsistent incoming material.' },
          { icon: 'Award', title: 'Enhance product quality', description: 'Consistent input material supports a consistent finished product.' },
          { icon: 'CheckCircle2', title: 'Lower rejection rates', description: 'Precise tolerances reduce out-of-spec rejections on your line.' },
          { icon: 'Gauge', title: 'Increase manufacturing speed', description: 'Production-ready coils move straight into your process.' },
          { icon: 'Recycle', title: 'Optimize material utilization', description: 'Accurate widths minimize trim loss and reprocessing.' },
        ],
      } },
      { blockType: 'mission-section', order: 9, anchorId: 'partnership', data: {
        label: 'PARTNERSHIP', title: 'Why Partner with Sonatek Steels?',
        bodyText: 'At Sonatek Steels, we believe steel processing should simplify manufacturing, not complicate it. Our experienced team works closely with customers to understand their production requirements and deliver steel solutions that improve operational performance, reduce processing time, and support long-term manufacturing success — whether your requirement is a recurring production order or a project-based supply.',
      } },
      { blockType: 'services-section', order: 10, anchorId: 'related', data: { title: 'OUR OTHER SERVICES', subtitle: 'Explore the full range of processing, supply, and distribution services available from Sonatek Steels.', services: SERVICES_DATA_7 } },
      { blockType: 'faq-section', order: 11, anchorId: 'faqs', data: { title: 'Frequently Asked Questions', items: [
        { question: 'What is coil slitting?', answer: 'Coil slitting is the process of cutting a wide steel coil into multiple narrower coils according to specific width requirements.' },
        { question: 'Which steel products can be slit?', answer: 'Cold Rolled (CR) and Hot Rolled (HR) steel coils can be processed into custom-width slit coils, subject to available processing capabilities.' },
        { question: 'What are the benefits of slit coils?', answer: 'Slit coils reduce material wastage, improve production efficiency, lower processing costs, and allow manufacturers to receive steel in production-ready widths.' },
        { question: 'Which industries commonly use slit coils?', answer: 'Automotive, electrical, furniture, tube manufacturing, roll forming, engineering, fabrication, and industrial equipment manufacturers.' },
        { question: 'Do you support bulk industrial orders?', answer: 'Yes. Sonatek Steels supports recurring production requirements, OEM supply, and project-based bulk orders.' },
      ] } },
      { blockType: 'cta-banner-industry', order: 12, data: {
        title: 'Precision Steel Starts with Precision Processing',
        description: 'Improve your manufacturing efficiency with professionally processed steel tailored to your production requirements. Partner with Sonatek Steels for dependable coil slitting solutions that help reduce waste, improve productivity, and keep your operations running smoothly.',
        btnText: 'Request a Quote', btnHref: '/contact-us',
        secondaryBtnText: 'Contact Our Processing Team', secondaryBtnHref: '/contact-us',
        bgImage: 'https://images.unsplash.com/photo-1541888946425-d81bb19480c5?w=1920&q=80',
      } },
    ],
  },
  {
    slug: 'services-cut-to-length', title: 'Services — Cut-To-Length Service', status: 'published',
    seo: {
      metaTitle: 'Cut-to-Length Steel Processing Services | CR & HR Sheets | Sonatek Steels',
      metaDescription: 'Precision Cut-to-Length steel processing for CR & HR coils. Custom sheet sizes, reduced wastage, fast dispatch, and reliable supply across India.',
      ogImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600&q=85',
    },
    blocks: [
      { blockType: 'service-hero', order: 0, anchorId: 'overview', data: {
        title: 'Custom Cut-to-Length Steel Sheets for Efficient Manufacturing',
        breadcrumbLabel: 'Cut-To-Length Service',
        description: "At Sonatek Steels, we provide precision Cut-to-Length (CTL) steel processing services for manufacturers who require steel sheets in exact dimensions, ready for production. Instead of purchasing full coils and investing additional time, labor, and machinery in cutting them, businesses can receive accurately cut steel sheets that are ready to use immediately, reducing material wastage and improving production efficiency. Whether you're in automotive, electrical, fabrication, engineering, furniture, or infrastructure, our precision cutting solutions ensure every sheet meets your production requirements.",
        image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600&q=85',
        ctaText: 'Request a Cut-to-Length Quote', ctaHref: '/contact-us',
        secondaryCtaText: 'Talk to a Steel Processing Expert', secondaryCtaHref: '/contact-us',
      } },
      { blockType: 'mission-section', order: 1, anchorId: 'what-is-cut-to-length', data: {
        label: 'OVERVIEW', title: 'What is Cut-to-Length (CTL)?',
        bodyText: 'Cut-to-Length is a steel processing method where large steel coils are uncoiled, leveled, and cut into flat sheets of specific lengths according to customer requirements. Unlike standard steel sheets, CTL processing allows manufacturers to receive material in customized dimensions, eliminating additional cutting processes at their facility. The result is ready-to-use steel sheets with consistent dimensions, clean edges, and improved flatness, helping businesses save time, reduce waste, and streamline production.',
      } },
      { blockType: 'process-steps', order: 2, anchorId: 'how-it-works', data: {
        label: 'PROCESS', title: 'Our Cut-to-Length Process',
        steps: [
          { title: 'Requirement Analysis', description: 'We understand your application, sheet dimensions, thickness, quantity, and production requirements.' },
          { title: 'Material Selection', description: 'Choose from our range of premium Cold Rolled (CR) Coils and Hot Rolled (HR) Coils.' },
          { title: 'Precision Cutting', description: 'Our processing line converts steel coils into sheets of the required length while maintaining dimensional accuracy and excellent flatness.' },
          { title: 'Quality Inspection', description: 'Every batch is inspected to ensure consistency, accurate dimensions, and high-quality output before dispatch.' },
          { title: 'Safe Packaging & Dispatch', description: 'Processed sheets are securely packed and delivered according to your production schedule.' },
        ],
      } },
      { blockType: 'icon-grid', order: 3, anchorId: 'benefits', data: {
        title: 'WHY CHOOSE CUT-TO-LENGTH STEEL?',
        subtitle: 'Every manufacturing process is different, and using standard-sized steel often results in unnecessary cutting, scrap generation, and additional processing costs. Our Cut-to-Length service provides steel exactly as your production line requires.',
        items: [
          { icon: 'Ruler', title: 'Custom Sheet Lengths', description: 'Sheets cut to the exact length your production line requires.' },
          { icon: 'Square', title: 'Improved Flatness', description: 'Levelled sheets with consistent flatness for immediate use.' },
          { icon: 'Recycle', title: 'Reduced Material Wastage', description: 'Precision lengths minimize trim loss and offcuts.' },
          { icon: 'Gauge', title: 'Higher Production Efficiency', description: 'Fewer processing steps once material reaches your facility.' },
          { icon: 'Zap', title: 'Faster Manufacturing', description: 'Production-ready sheets move straight into your process.' },
          { icon: 'DollarSign', title: 'Lower Processing Costs', description: 'Reduces the need for in-house cutting equipment and labour.' },
          { icon: 'Boxes', title: 'Better Inventory Management', description: 'Stock exact sheet sizes instead of oversized coil.' },
          { icon: 'PackageCheck', title: 'Ready-to-Use Material', description: 'Sheets arrive ready to feed directly into your process.' },
          { icon: 'CheckCircle2', title: 'Accurate Dimensions', description: 'Consistent dimensions across every batch and every sheet.' },
          { icon: 'Sparkles', title: 'Clean & Consistent Cuts', description: 'Clean edges with dimensional accuracy on every sheet.' },
        ],
      } },
      { blockType: 'icon-grid', order: 4, anchorId: 'industries', data: {
        title: 'INDUSTRIES WE SERVE',
        subtitle: 'Our Cut-to-Length services support a wide range of industries where precision, consistency, and production efficiency are essential.',
        items: [
          { icon: 'Car', title: 'Automotive', description: 'Steel sheets for body parts, structural components, brackets, and assemblies.' },
          { icon: 'PanelsTopLeft', title: 'Electrical Panel Manufacturing', description: 'Custom-sized sheets for electrical cabinets, control panels, and enclosures.' },
          { icon: 'Armchair', title: 'Furniture Manufacturing', description: 'Steel sheets for office furniture, storage systems, modular furniture, and industrial shelving.' },
          { icon: 'Wind', title: 'HVAC Industry', description: 'Material for ducts, ventilation systems, air handling units, and cooling equipment.' },
          { icon: 'Factory', title: 'Heavy Engineering', description: 'Precision steel sheets for machinery, equipment, and industrial fabrication.' },
          { icon: 'Building2', title: 'Infrastructure & Construction', description: 'Steel for industrial buildings, warehouses, fabrication, and engineering projects.' },
          { icon: 'Settings2', title: 'OEM Manufacturing', description: 'Reliable material for high-volume manufacturing operations and production lines.' },
        ],
      } },
      { blockType: 'how-we-can-help', order: 5, anchorId: 'applications', data: {
        label: 'APPLICATIONS', title: 'WHERE CUT-TO-LENGTH SHEETS ARE USED',
        subtitle: 'Our processed sheets are commonly used in laser cutting, CNC punching, press components, fabrication, welding, bending, and stamping operations.',
        items: [
          { title: 'Automotive', image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80', href: '/industries/automotive' },
          { title: 'Electrical Cabinets', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80', href: '/industries/electrical-panel' },
          { title: 'Machine Manufacturing', image: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=800&q=80', href: '/industries/working-machinery' },
          { title: 'Industrial Equipment & Storage Systems', image: 'https://images.unsplash.com/photo-1494412519320-aa613dfb7738?w=800&q=80', href: '/industries/warehousing-logistics' },
          { title: 'Structural Components', image: 'https://images.unsplash.com/photo-1541888946425-d81bb19480c5?w=800&q=80', href: '/industries/construction' },
          { title: 'Furniture & Shelving', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/industries/furniture' },
        ],
      } },
      { blockType: 'built-to-deliver', order: 6, anchorId: 'advantages', data: {
        label: 'WHY SONATEK STEELS', title: 'Why Manufacturers Choose Sonatek Steels',
        subtitle: 'At Sonatek, we understand that manufacturing depends on consistency, speed, and reliability. Our Cut-to-Length solutions help businesses reduce operational costs while ensuring steel reaches the production floor exactly as required.',
        points: [
          { icon: 'ShieldCheck', title: 'Premium CR & HR Steel', description: 'Sourced from certified primary producers for consistent quality.' },
          { icon: 'Ruler', title: 'Precision Processing', description: 'Automated leveling and shearing lines built to hold tight tolerances.' },
          { icon: 'Warehouse', title: 'Ready Stock Availability', description: 'Stocked master coils ready to process without long lead times.' },
          { icon: 'Zap', title: 'Fast Turnaround', description: 'Streamlined processing-to-dispatch turnaround.' },
          { icon: 'CheckCircle2', title: 'Consistent Sheet Dimensions', description: 'Reliable length, flatness, and squareness on every batch.' },
          { icon: 'BadgeCheck', title: 'Reliable Quality', description: 'Consistent availability backed by a dependable procurement network.' },
          { icon: 'Boxes', title: 'Bulk Processing Capability', description: 'Support for both trial orders and large production runs.' },
          { icon: 'Globe', title: 'Pan-India Delivery', description: 'Coordinated dispatch and delivery across the country.' },
          { icon: 'Headset', title: 'Dedicated B2B Support', description: 'A responsive team throughout your order and processing cycle.' },
        ],
      } },
      { blockType: 'mission-section', order: 7, anchorId: 'quality', data: {
        label: 'SAVINGS', title: 'Why Cut-to-Length Saves Your Business Money',
        bodyText: "Purchasing standard coils often means investing in additional machinery, manpower, storage space, and processing time. With Sonatek's Cut-to-Length service, manufacturers receive production-ready sheets that minimize scrap, reduce labour costs, improve production speed, lower handling costs, optimize inventory, and increase operational efficiency — resulting in a smoother manufacturing process with reduced downtime and better overall productivity.",
      } },
      { blockType: 'mission-section', order: 9, anchorId: 'partnership', data: {
        label: 'PARTNERSHIP', title: 'Why Partner with Sonatek Steels?',
        bodyText: 'We are more than a steel supplier — we are a trusted manufacturing partner committed to delivering precision, consistency, and dependable service. Whether you require a one-time order or recurring industrial supply, our team works closely with you to understand your production needs and provide steel solutions that add value to your business.',
      } },
      { blockType: 'services-section', order: 10, anchorId: 'related', data: { title: 'OUR OTHER SERVICES', subtitle: 'Explore the full range of processing, supply, and distribution services available from Sonatek Steels.', services: SERVICES_DATA_7 } },
      { blockType: 'faq-section', order: 11, anchorId: 'faqs', data: { title: 'Frequently Asked Questions', items: [
        { question: 'What is Cut-to-Length steel processing?', answer: 'Cut-to-Length is the process of converting steel coils into flat sheets of customized lengths based on customer requirements.' },
        { question: 'Which steel products can be processed?', answer: 'We provide Cut-to-Length processing for both Cold Rolled (CR) and Hot Rolled (HR) steel coils.' },
        { question: 'Can I request custom sheet sizes?', answer: 'Yes. We process steel according to your required sheet length and production specifications.' },
        { question: 'Which industries benefit from CTL processing?', answer: 'Automotive, fabrication, engineering, electrical panels, furniture, HVAC, OEM manufacturing, and infrastructure industries.' },
        { question: 'Do you support bulk industrial orders?', answer: 'Yes. We cater to bulk requirements for manufacturers, OEMs, fabricators, EPC contractors, and industrial projects across India.' },
      ] } },
      { blockType: 'cta-banner-industry', order: 12, data: {
        title: 'Ready to Simplify Your Steel Processing?',
        description: 'Get precision-cut steel sheets that fit your production needs and reduce processing time. Whether you need standard or customized dimensions, Sonatek Steels is ready to support your manufacturing operations with dependable Cut-to-Length processing and reliable delivery.',
        btnText: 'Request a Quote Today', btnHref: '/contact-us',
        secondaryBtnText: 'Talk to a Steel Processing Expert', secondaryBtnHref: '/contact-us',
        bgImage: 'https://images.unsplash.com/photo-1541888946425-d81bb19480c5?w=1920&q=80',
      } },
    ],
  },
  {
    slug: 'services-luster-steel-processing', title: 'Services — Luster Steel Processing', status: 'published',
    seo: {
      metaTitle: 'Lustre Steel Processing Services | Premium Surface Finish | Sonatek Steels',
      metaDescription: 'Premium Lustre Steel Processing services for CR & HR steel. Superior surface finish, improved coating quality, reliable processing, and Pan-India delivery.',
      ogImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1600&q=85',
    },
    blocks: [
      { blockType: 'service-hero', order: 0, anchorId: 'overview', data: {
        title: 'Premium Lustre Steel Processing for Superior Surface Quality & Manufacturing Performance',
        breadcrumbLabel: 'Luster Steel Processing',
        description: "In today's competitive manufacturing environment, surface quality is just as important as strength and durability. At Sonatek Steels, our Lustre Steel Processing services are designed to deliver steel with a cleaner, smoother, and more consistent surface finish that enhances both appearance and performance. Whether your products require painting, powder coating, fabrication, or precision forming, our processed steel ensures excellent finish quality, improved workability, and reliable manufacturing results.",
        image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1600&q=85',
        ctaText: 'Request a Custom Quote', ctaHref: '/contact-us',
        secondaryCtaText: 'Talk to a Steel Processing Expert', secondaryCtaHref: '/contact-us',
      } },
      { blockType: 'mission-section', order: 1, anchorId: 'what-is-luster-steel-processing', data: {
        label: 'OVERVIEW', title: 'What is Lustre Steel Processing?',
        bodyText: "Lustre Steel Processing is a value-added processing solution that enhances the surface quality of steel before it enters the manufacturing process. By ensuring a cleaner, smoother, and more uniform surface, manufacturers can achieve better coating adhesion, improved aesthetics, easier fabrication, and consistent production quality. For industries where the final product's appearance and finish matter, lustre processed steel provides a significant advantage over conventional material.",
      } },
      { blockType: 'process-steps', order: 2, anchorId: 'how-it-works', data: {
        label: 'PROCESS', title: 'Our Processing Workflow',
        steps: [
          { title: 'Requirement Consultation', description: 'We understand your application, finishing requirements, and production process.' },
          { title: 'Material Selection', description: 'Select premium Cold Rolled (CR) or Hot Rolled (HR) steel based on your manufacturing needs.' },
          { title: 'Lustre Steel Processing', description: 'Steel undergoes controlled processing to achieve the required surface quality and consistency.' },
          { title: 'Quality Inspection', description: 'Each batch is inspected to ensure the required surface finish and processing standards are maintained.' },
          { title: 'Packaging & Dispatch', description: 'Processed steel is securely packed and delivered according to your production schedule.' },
        ],
      } },
      { blockType: 'icon-grid', order: 3, anchorId: 'benefits', data: {
        title: 'WHY CHOOSE LUSTRE STEEL PROCESSING?',
        subtitle: 'Steel with superior surface quality contributes to better manufacturing efficiency and improved finished products. Manufacturers choose lustre processed steel because it helps:',
        items: [
          { icon: 'Sparkles', title: 'Improve Surface Appearance', description: 'A clean, consistent surface finish suited to visible, appearance-critical parts.' },
          { icon: 'Droplet', title: 'Enhance Paint & Powder Coating Adhesion', description: 'A consistent surface improves paint and powder coating performance.' },
          { icon: 'Recycle', title: 'Reduce Surface Imperfections', description: 'Controlled processing minimizes scratches, stains, and defects.' },
          { icon: 'Settings2', title: 'Improve Fabrication Quality', description: 'Manufacturing-ready steel reduces additional surface preparation before production.' },
          { icon: 'CheckCircle2', title: 'Increase Product Consistency', description: 'Every batch is processed to the same surface quality standard.' },
          { icon: 'DollarSign', title: 'Reduce Rework & Rejection', description: 'Consistent surface quality minimizes defects and production delays.' },
          { icon: 'Award', title: 'Improve Overall Product Value', description: 'Premium surface finish enhances the overall quality and perceived value of manufactured products.' },
          { icon: 'PackageCheck', title: 'Deliver Premium Finished Products', description: 'Processed steel supports a higher-quality end product.' },
        ],
      } },
      { blockType: 'icon-grid', order: 4, anchorId: 'industries', data: {
        title: 'INDUSTRIES THAT BENEFIT FROM LUSTRE STEEL PROCESSING',
        subtitle: 'Our surface finishing services support a wide range of manufacturing industries, including:',
        items: [
          { icon: 'Car', title: 'Automotive Industry', description: 'High-quality steel for body components, brackets, structural parts, and precision automotive applications requiring excellent surface finish.' },
          { icon: 'PanelsTopLeft', title: 'Electrical Panel Manufacturing', description: 'Processed steel for electrical cabinets, control panels, enclosures, and industrial electrical equipment.' },
          { icon: 'Armchair', title: 'Furniture Manufacturing', description: 'Premium surface-finished steel for office furniture, storage systems, modular furniture, and industrial shelving.' },
          { icon: 'Wind', title: 'HVAC Industry', description: 'Steel suitable for air ducts, ventilation systems, cooling equipment, and HVAC assemblies requiring consistent coating quality.' },
          { icon: 'Factory', title: 'Heavy Engineering', description: 'Reliable surface quality for fabricated machinery, equipment covers, and engineering components.' },
          { icon: 'Package', title: 'Home Appliances', description: 'Smooth surface steel ideal for refrigerators, washing machines, cabinets, and other consumer appliances.' },
          { icon: 'Settings2', title: 'OEM Manufacturing', description: 'Consistent processed steel for high-volume production requiring reliable surface quality and repeatable manufacturing performance.' },
        ],
      } },
      { blockType: 'how-we-can-help', order: 5, anchorId: 'applications', data: {
        label: 'APPLICATIONS', title: 'OUR LUSTRE STEEL PROCESSING SOLUTIONS',
        subtitle: 'Premium surface enhancement, coating preparation, and manufacturing-ready steel — processed and delivered as bulk industrial requirements demand.',
        items: [
          { title: 'Premium Surface Enhancement', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/products' },
          { title: 'Automotive Body Components', image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80', href: '/industries/automotive' },
          { title: 'Furniture & Architectural Fittings', image: 'https://images.unsplash.com/photo-1469289759076-d1484757abc3?w=800&q=80', href: '/industries/furniture' },
          { title: 'Surface Preparation for Coating', image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', href: '/custom-steel-processing' },
          { title: 'Electrical Enclosures', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80', href: '/industries/electrical-panel' },
          { title: 'Heavy Engineering Components', image: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=800&q=80', href: '/industries/heavy-engineering' },
        ],
      } },
      { blockType: 'built-to-deliver', order: 6, anchorId: 'advantages', data: {
        label: 'WHY SONATEK STEELS', title: 'Why Manufacturers Prefer Lustre Steel Processing',
        subtitle: 'At Sonatek, we understand that quality steel begins with quality processing.',
        points: [
          { icon: 'Sparkles', title: 'Superior Surface Finish', description: 'Cleaner and smoother steel improves the appearance of finished products while enhancing customer satisfaction.' },
          { icon: 'Droplet', title: 'Better Coating Performance', description: 'A consistent surface improves paint and powder coating adhesion, creating long-lasting and visually appealing finishes.' },
          { icon: 'Zap', title: 'Improved Manufacturing Efficiency', description: 'Manufacturing-ready steel reduces additional surface preparation before production.' },
          { icon: 'Recycle', title: 'Reduced Rework', description: 'Consistent surface quality minimizes defects, reducing production delays and rejection rates.' },
          { icon: 'Award', title: 'Higher Product Value', description: 'Premium surface finish enhances the overall quality and perceived value of manufactured products.' },
          { icon: 'BadgeCheck', title: 'Consistent Quality Standards', description: 'Every order is processed with attention to detail to deliver reliable and repeatable results.' },
        ],
      } },
      { blockType: 'mission-section', order: 9, anchorId: 'partnership', data: {
        label: 'PARTNERSHIP', title: "Let's Build Better Products Together",
        bodyText: "Superior manufacturing starts with superior materials. With Sonatek Steels' Lustre Steel Processing services, you receive steel that's engineered for better appearance, improved manufacturing efficiency, and consistent production quality. Request a Custom Processing Quote today and experience premium steel solutions designed to elevate your manufacturing standards.",
      } },
      { blockType: 'services-section', order: 10, anchorId: 'related', data: { title: 'OUR OTHER SERVICES', subtitle: 'Explore the full range of processing, supply, and distribution services available from Sonatek Steels.', services: SERVICES_DATA_7 } },
      { blockType: 'faq-section', order: 11, anchorId: 'faqs', data: { title: 'Frequently Asked Questions', items: [
        { question: 'What is Lustre Steel Processing?', answer: 'Lustre Steel Processing is a value-added service that enhances the surface quality of steel, making it more suitable for fabrication, painting, powder coating, and premium industrial applications.' },
        { question: 'Which steel products can be processed?', answer: 'We provide Lustre Steel Processing solutions for both Cold Rolled (CR) and Hot Rolled (HR) steel products.' },
        { question: 'Which industries benefit from Lustre Steel Processing?', answer: 'Automotive, furniture, electrical panels, HVAC, appliances, engineering, fabrication, and OEM manufacturing industries benefit from improved surface quality.' },
        { question: 'Is Lustre Steel suitable for painting and powder coating?', answer: 'Yes. A smoother and more consistent surface improves coating adhesion, resulting in better finish quality and durability.' },
        { question: 'Do you support bulk industrial orders?', answer: 'Absolutely. We support recurring supply requirements and bulk industrial processing for manufacturers across India.' },
      ] } },
      { blockType: 'cta-banner-industry', order: 12, data: {
        title: 'Request a Custom Processing Quote Today',
        description: "Experience premium steel solutions designed to elevate your manufacturing standards, with dependable Lustre Steel Processing that helps improve appearance, reduce rework, and keep your operations running smoothly.",
        btnText: 'Request a Custom Quote', btnHref: '/contact-us',
        secondaryBtnText: 'Talk to a Steel Processing Expert', secondaryBtnHref: '/contact-us',
        bgImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1920&q=80',
      } },
    ],
  },
  {
    slug: 'services-bulk-industrial-supply', title: 'Services — Bulk Industrial Supply', status: 'published',
    seo: {
      metaTitle: 'Bulk Industrial Steel Supply | CR & HR Steel Supplier | Sonatek Steels',
      metaDescription: 'Bulk industrial steel supply for CR & HR coils and sheets. Reliable inventory, scheduled deliveries, Pan-India logistics, and long-term supply solutions.',
      ogImage: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=1600&q=85',
    },
    blocks: [
      { blockType: 'service-hero', order: 0, anchorId: 'overview', data: {
        title: 'Reliable Bulk Steel Supply for Large-Scale Manufacturing & Industrial Requirements',
        breadcrumbLabel: 'Bulk Industrial Supply',
        description: "When your production depends on a continuous supply of high-quality steel, you need more than just a supplier — you need a dependable supply partner. At Sonatek Steels, we specialize in Bulk Industrial Steel Supply, ensuring manufacturers, OEMs, EPC contractors, fabricators, and infrastructure companies receive premium steel products on time and in the required quantities. Whether your requirement is for recurring production, project-based procurement, or high-volume industrial manufacturing, Sonatek is committed to keeping your operations running smoothly.",
        image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=1600&q=85',
        ctaText: 'Request a Bulk Supply Quote', ctaHref: '/contact-us',
        secondaryCtaText: 'Talk to a Steel Supply Expert', secondaryCtaHref: '/contact-us',
      } },
      { blockType: 'mission-section', order: 1, anchorId: 'what-is-bulk-industrial-supply', data: {
        label: 'OVERVIEW', title: 'What is Bulk Industrial Steel Supply?',
        bodyText: 'Bulk Industrial Steel Supply is a comprehensive supply solution designed for businesses requiring large volumes of steel on a regular or project basis. Instead of placing multiple small orders, manufacturers can streamline procurement through planned bulk purchasing, ensuring consistent inventory, better supply chain management, and uninterrupted production. Our bulk supply solutions are built around reliability, quality assurance, and timely deliveries to help businesses maintain operational efficiency.',
      } },
      { blockType: 'process-steps', order: 2, anchorId: 'how-it-works', data: {
        label: 'PROCESS', title: 'Our Supply Process',
        steps: [
          { title: 'Requirement Consultation', description: 'We assess your production volume, product requirements, and delivery schedule.' },
          { title: 'Material Planning', description: 'Our team confirms inventory availability and develops a supply plan aligned with your operational needs.' },
          { title: 'Order Confirmation', description: 'Bulk orders are scheduled and prepared for processing and dispatch.' },
          { title: 'Quality Inspection', description: 'All materials undergo quality checks before dispatch to ensure consistency and reliability.' },
          { title: 'Delivery & Ongoing Support', description: 'Steel is delivered according to agreed schedules, with continuous support for future procurement needs.' },
        ],
      } },
      { blockType: 'icon-grid', order: 3, anchorId: 'benefits', data: {
        title: 'WHY CHOOSE BULK INDUSTRIAL SUPPLY?',
        subtitle: 'Managing large-scale steel procurement comes with challenges such as fluctuating inventory, delayed deliveries, and inconsistent supply. Our bulk supply solutions help manufacturers overcome these challenges.',
        items: [
          { icon: 'ShieldCheck', title: 'Reliable Material Availability', description: 'Consistent access to premium CR and HR steel for recurring or project-based requirements.' },
          { icon: 'BadgeCheck', title: 'Consistent Product Quality', description: 'Every coil, sheet, or plate in a bulk order is sourced and quality-verified to the same standard.' },
          { icon: 'Truck', title: 'Scheduled Deliveries', description: 'Receive steel according to your production schedule instead of managing excessive inventory.' },
          { icon: 'Zap', title: 'Faster Procurement', description: 'Streamlined bulk purchasing reduces the overhead of multiple small orders.' },
          { icon: 'Clock', title: 'Reduced Lead Time', description: 'Ready inventory and planned dispatch reduce waiting time on large orders.' },
          { icon: 'Boxes', title: 'Better Inventory Planning', description: 'Our team assists in forecasting requirements and planning procurement cycles.' },
          { icon: 'DollarSign', title: 'Cost-Effective Supply Management', description: 'Volume sourcing supports more competitive bulk pricing.' },
          { icon: 'Handshake', title: 'Long-Term Supply Support', description: 'Dependable supply programs for recurring and project-based requirements.' },
        ],
      } },
      { blockType: 'icon-grid', order: 4, anchorId: 'industries', data: {
        title: 'INDUSTRIES THAT BENEFIT FROM BULK INDUSTRIAL SUPPLY',
        subtitle: 'Our bulk supply services support a wide range of large-scale buyers, including:',
        items: [
          { icon: 'Car', title: 'Automotive Industry', description: 'Bulk steel supply for vehicle manufacturing, structural components, and precision automotive applications.' },
          { icon: 'Factory', title: 'Heavy Engineering', description: 'Reliable material for machinery manufacturing, industrial equipment, and heavy fabrication.' },
          { icon: 'Building2', title: 'Infrastructure & Construction', description: 'Bulk procurement support for industrial buildings, warehouses, commercial projects, and infrastructure development.' },
          { icon: 'PanelsTopLeft', title: 'Electrical Panel Manufacturing', description: 'Consistent supply of premium steel for electrical cabinets, enclosures, and industrial control systems.' },
          { icon: 'Armchair', title: 'Furniture Manufacturing', description: 'Large-volume steel supply for office furniture, storage systems, modular furniture, and industrial shelving.' },
          { icon: 'Wind', title: 'HVAC Industry', description: 'Reliable steel supply for ventilation systems, ducts, cooling equipment, and HVAC assemblies.' },
          { icon: 'Settings2', title: 'OEM Manufacturing', description: 'Long-term material support for high-volume manufacturing operations requiring consistent quality and dependable supply.' },
        ],
      } },
      { blockType: 'how-we-can-help', order: 5, anchorId: 'applications', data: {
        label: 'APPLICATIONS', title: 'OUR BULK INDUSTRIAL SUPPLY SOLUTIONS',
        subtitle: 'From bulk procurement and scheduled deliveries to project-based supply and inventory planning support, our bulk solutions keep large-volume operations running smoothly.',
        items: [
          { title: 'Bulk Steel Procurement', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/industrial-procurement' },
          { title: 'Project-Based Steel Supply', image: 'https://images.unsplash.com/photo-1727504172725-14acb4f32655?q=80&w=1170', href: '/project-based-steel' },
          { title: 'Automotive Industry', image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80', href: '/industries/automotive' },
          { title: 'Heavy Engineering', image: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=800&q=80', href: '/industries/heavy-engineering' },
          { title: 'Infrastructure & Construction', image: 'https://images.unsplash.com/photo-1541888946425-d81bb19480c5?w=800&q=80', href: '/industries/construction' },
          { title: 'Warehousing & Logistics', image: 'https://images.unsplash.com/photo-1494412519320-aa613dfb7738?w=800&q=80', href: '/industries/warehousing-logistics' },
        ],
      } },
      { blockType: 'built-to-deliver', order: 6, anchorId: 'advantages', data: {
        label: 'WHY SONATEK STEELS', title: 'Why Manufacturers Prefer Bulk Industrial Supply',
        subtitle: 'At Sonatek, we understand that dependable steel supply is essential for maintaining production efficiency and meeting project deadlines.',
        points: [
          { icon: 'ShieldCheck', title: 'Uninterrupted Production', description: 'Consistent material availability helps avoid costly production delays.' },
          { icon: 'Warehouse', title: 'Reliable Inventory', description: 'Access to ready stock ensures quicker order fulfillment and reduced lead times.' },
          { icon: 'Boxes', title: 'Better Procurement Planning', description: 'Bulk purchasing simplifies procurement while improving operational efficiency.' },
          { icon: 'BadgeCheck', title: 'Lower Supply Chain Risk', description: 'Planned deliveries reduce uncertainty and support continuous manufacturing.' },
          { icon: 'DollarSign', title: 'Cost Optimization', description: 'Bulk supply programs help businesses optimize procurement and logistics costs over the long term.' },
          { icon: 'Headset', title: 'Dedicated Business Support', description: 'Our experienced team works closely with customers to understand their production and supply requirements.' },
        ],
      } },
      { blockType: 'mission-section', order: 9, anchorId: 'partnership', data: {
        label: 'PARTNERSHIP', title: 'Power Your Production with Reliable Bulk Steel Supply',
        bodyText: "Whether you're managing a manufacturing plant, executing an infrastructure project, or operating a high-volume production facility, Sonatek Steels provides the inventory, expertise, and logistics support needed to keep your operations moving. Partner with Sonatek for dependable bulk steel supply, responsive service, and long-term procurement confidence.",
      } },
      { blockType: 'services-section', order: 10, anchorId: 'related', data: { title: 'OUR OTHER SERVICES', subtitle: 'Explore the full range of processing, supply, and distribution services available from Sonatek Steels.', services: SERVICES_DATA_7 } },
      { blockType: 'faq-section', order: 11, anchorId: 'faqs', data: { title: 'Frequently Asked Questions', items: [
        { question: 'What products are available for bulk supply?', answer: 'We supply Cold Rolled (CR) Coils, Cold Rolled (CR) Sheets, Hot Rolled (HR) Coils, and Hot Rolled (HR) Sheets in bulk quantities.' },
        { question: 'Can Sonatek handle recurring industrial requirements?', answer: 'Yes. We support monthly, quarterly, and annual supply programs for manufacturers and OEMs.' },
        { question: 'Do you provide project-based steel supply?', answer: 'Absolutely. We supply steel for infrastructure projects, engineering companies, EPC contractors, and industrial developments.' },
        { question: 'Do you deliver across India?', answer: 'Yes. Our logistics network supports bulk deliveries across North India and Pan-India based on customer requirements.' },
        { question: 'Can I discuss customized delivery schedules?', answer: 'Yes. We work with customers to create supply schedules that align with production timelines and inventory planning.' },
      ] } },
      { blockType: 'cta-banner-industry', order: 12, data: {
        title: 'Request a Bulk Supply Quote Today',
        description: 'Secure a reliable steel supply partner for your business — share your required tonnage, grade, and delivery timeline and we will confirm availability and a coordinated dispatch plan.',
        btnText: 'Request a Bulk Supply Quote', btnHref: '/contact-us',
        secondaryBtnText: 'Talk to a Steel Supply Expert', secondaryBtnHref: '/contact-us',
        bgImage: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1920&q=80',
      } },
    ],
  },
  {
    slug: 'services-logistics-delivery', title: 'Services — Delivery & Logistics Service', status: 'published',
    seo: {
      metaTitle: 'Steel Delivery & Logistics Services India | Sonatek Steels',
      metaDescription: 'Reliable steel delivery and logistics services for CR & HR coils and sheets. Scheduled dispatches, bulk transportation, and Pan-India industrial delivery.',
      ogImage: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=1600&q=85',
    },
    blocks: [
      { blockType: 'service-hero', order: 0, anchorId: 'overview', data: {
        title: 'Reliable Steel Delivery & Logistics Solutions That Keep Your Business Moving',
        breadcrumbLabel: 'Delivery & Logistics Service',
        description: "At Sonatek Steels, we understand that timely delivery is just as important as the quality of steel. That's why we offer dependable Delivery & Logistics Services designed to ensure your steel reaches your facility safely, efficiently, and on schedule. Whether you're a manufacturer, OEM, fabricator, infrastructure company, or EPC contractor, our logistics network is built to support businesses with reliable transportation, planned dispatches, and seamless material movement across India.",
        image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=1600&q=85',
        ctaText: 'Request a Delivery Quote', ctaHref: '/contact-us',
        secondaryCtaText: 'Talk to Our Logistics Team', secondaryCtaHref: '/contact-us',
      } },
      { blockType: 'mission-section', order: 1, anchorId: 'what-is-our-delivery-service', data: {
        label: 'OVERVIEW', title: 'What are Delivery & Logistics Services?',
        bodyText: 'Delivery & Logistics Services involve the efficient planning, coordination, transportation, and delivery of steel products from our warehouse to your manufacturing facility or project site. Our logistics solutions are designed to ensure that businesses receive the right material, in the right quantity, at the right time — helping maintain uninterrupted production and efficient supply chain operations. Whether your requirement is a single dispatch or recurring deliveries, Sonatek provides dependable logistics support tailored to your business needs.',
      } },
      { blockType: 'process-steps', order: 2, anchorId: 'how-it-works', data: {
        label: 'PROCESS', title: 'Our Delivery Process',
        steps: [
          { title: 'Order Confirmation', description: 'Our team confirms product availability, quantity, and delivery requirements.' },
          { title: 'Dispatch Planning', description: 'Delivery schedules are planned based on your production timelines and preferred delivery dates.' },
          { title: 'Material Preparation', description: 'Steel products are inspected, packed, and prepared for safe transportation.' },
          { title: 'Quality Check', description: 'Every order undergoes a final verification before dispatch to ensure accuracy and consistency.' },
          { title: 'Transportation & Delivery', description: 'Material is transported safely and delivered to your manufacturing facility or project site on schedule.' },
        ],
      } },
      { blockType: 'icon-grid', order: 3, anchorId: 'benefits', data: {
        title: 'WHY CHOOSE OUR DELIVERY & LOGISTICS SERVICES?',
        subtitle: 'Efficient logistics play a critical role in maintaining productivity and meeting production deadlines. Our delivery solutions help businesses by providing:',
        items: [
          { icon: 'Clock', title: 'On-Time Deliveries', description: 'Reliable dispatch schedules help maintain production timelines and minimize downtime.' },
          { icon: 'ShieldCheck', title: 'Safe Material Handling', description: 'Steel is handled and transported with care to ensure it reaches your facility in excellent condition.' },
          { icon: 'Route', title: 'Planned Dispatches', description: 'Dispatches matched to the right vehicle and route for your material.' },
          { icon: 'Truck', title: 'Reliable Transportation', description: 'Coordinated road transport built specifically for flat steel dispatch.' },
          { icon: 'Gauge', title: 'Reduced Supply Chain Delays', description: 'Efficient coordination helps reduce procurement challenges and improves operational continuity.' },
          { icon: 'Boxes', title: 'Better Inventory Management', description: 'Scheduled deliveries help improve production planning and reduce storage costs.' },
          { icon: 'Globe', title: 'Nationwide Delivery Support', description: 'Our logistics network enables us to serve customers across North India and beyond.' },
          { icon: 'Headset', title: 'Dedicated Logistics Coordination', description: 'Our experienced team provides continuous coordination from order confirmation to final delivery.' },
        ],
      } },
      { blockType: 'icon-grid', order: 4, anchorId: 'industries', data: {
        title: 'INDUSTRIES THAT BENEFIT FROM OUR LOGISTICS SERVICES',
        subtitle: 'Our delivery and logistics service supports a wide range of manufacturing and project industries, including:',
        items: [
          { icon: 'Car', title: 'Automotive Industry', description: 'Reliable deliveries for continuous automotive production and component manufacturing.' },
          { icon: 'Factory', title: 'Heavy Engineering', description: 'Timely transportation of steel for machinery manufacturing and industrial fabrication.' },
          { icon: 'Building2', title: 'Infrastructure & Construction', description: 'Scheduled deliveries for industrial buildings, warehouses, and large-scale infrastructure projects.' },
          { icon: 'PanelsTopLeft', title: 'Electrical Panel Manufacturing', description: 'Consistent steel supply for uninterrupted production of electrical cabinets and enclosures.' },
          { icon: 'Armchair', title: 'Furniture Manufacturing', description: 'Reliable material deliveries supporting high-volume furniture manufacturing operations.' },
          { icon: 'Wind', title: 'HVAC Industry', description: 'Efficient transportation of steel used in ventilation systems, ducts, and HVAC equipment.' },
          { icon: 'Settings2', title: 'OEM Manufacturing', description: 'Dependable logistics solutions supporting recurring procurement and production schedules.' },
        ],
      } },
      { blockType: 'how-we-can-help', order: 5, anchorId: 'cargo', data: {
        label: 'OUR SOLUTIONS', title: 'OUR DELIVERY & LOGISTICS SOLUTIONS',
        subtitle: 'From scheduled deliveries and bulk transportation to project-based logistics and Pan-India delivery support, our network keeps your material moving.',
        items: [
          { title: 'Scheduled Deliveries', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', href: '/products' },
          { title: 'Bulk Material Transportation', image: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80', href: '/services/bulk-industrial-supply' },
          { title: 'Project-Based Logistics', image: 'https://images.unsplash.com/photo-1727504172725-14acb4f32655?q=80&w=1170', href: '/project-based-steel' },
          { title: 'Warehouse-to-Plant Delivery', image: 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=800&q=80', href: '/industries/warehousing-logistics' },
          { title: 'Automotive Components', image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80', href: '/industries/automotive' },
          { title: 'Construction Sites', image: 'https://images.unsplash.com/photo-1541888946425-d81bb19480c5?w=800&q=80', href: '/industries/construction' },
          { title: 'Electrical Equipment', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80', href: '/industries/electrical-panel' },
          { title: 'Heavy Engineering', image: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=800&q=80', href: '/industries/heavy-engineering' },
        ],
      } },
      { blockType: 'built-to-deliver', order: 6, anchorId: 'advantages', data: {
        label: 'WHY SONATEK STEELS', title: 'Why Manufacturers Prefer Our Delivery & Logistics Services',
        subtitle: 'We understand that ordering steel is only half the job — it still has to arrive intact and on time.',
        points: [
          { icon: 'Clock', title: 'On-Time Delivery', description: 'Reliable dispatch schedules help maintain production timelines and minimize downtime.' },
          { icon: 'ShieldCheck', title: 'Safe Transportation', description: 'Steel is handled and transported with care to ensure it reaches your facility in excellent condition.' },
          { icon: 'BadgeCheck', title: 'Reliable Supply Chain', description: 'Efficient coordination helps reduce procurement challenges and improves operational continuity.' },
          { icon: 'Route', title: 'Flexible Delivery Scheduling', description: 'Deliveries can be planned according to production requirements and project milestones.' },
          { icon: 'Globe', title: 'Nationwide Coverage', description: 'We support businesses across North India and coordinate deliveries for customers throughout India.' },
          { icon: 'Headset', title: 'Dedicated Logistics Support', description: 'Our experienced team provides continuous coordination from order confirmation to final delivery.' },
        ],
      } },
      { blockType: 'mission-section', order: 9, anchorId: 'partnership', data: {
        label: 'PARTNERSHIP', title: 'Delivering Steel with Speed, Reliability & Confidence',
        bodyText: "Reliable logistics are the backbone of every successful manufacturing operation. At Sonatek Steels, we combine quality steel, efficient transportation, and responsive logistics support to ensure your material reaches you safely and on time. Whether you're managing daily production, a major infrastructure project, or long-term industrial procurement, Sonatek is your trusted logistics and steel supply partner.",
      } },
      { blockType: 'services-section', order: 10, anchorId: 'related', data: { title: 'OUR OTHER SERVICES', subtitle: 'Explore the full range of processing, supply, and distribution services available from Sonatek Steels.', services: SERVICES_DATA_7 } },
      { blockType: 'faq-section', order: 11, anchorId: 'faqs', data: { title: 'Frequently Asked Questions', items: [
        { question: 'Do you deliver steel across India?', answer: 'Yes. We provide reliable delivery services across North India and coordinate shipments for customers throughout India.' },
        { question: 'What products do you deliver?', answer: 'We deliver Cold Rolled (CR) Coils, Cold Rolled (CR) Sheets, Hot Rolled (HR) Coils, and Hot Rolled (HR) Sheets.' },
        { question: 'Can deliveries be scheduled according to production requirements?', answer: 'Yes. We work closely with customers to plan dispatches based on production schedules and project timelines.' },
        { question: 'Do you handle bulk industrial deliveries?', answer: 'Absolutely. We support bulk transportation for manufacturers, OEMs, EPC contractors, and industrial projects.' },
        { question: 'Is logistics support available for recurring orders?', answer: 'Yes. We provide ongoing logistics coordination for customers with regular procurement and long-term supply requirements.' },
      ] } },
      { blockType: 'cta-banner-industry', order: 12, data: {
        title: 'Request a Delivery Quote Today',
        description: "Tell us your site location — we'll confirm regional coverage and expected delivery timing. Experience dependable steel logistics designed around your business.",
        btnText: 'Request a Delivery Quote', btnHref: '/contact-us',
        secondaryBtnText: 'Talk to Our Logistics Team', secondaryBtnHref: '/contact-us',
        bgImage: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=1920&q=85',
      } },
    ],
  },
];

// Links to append to the navbar's "Solutions" mega-menu "SERVICES" section.
export const NAVBAR_SERVICES_LINKS = [
  { label: 'Coil Slitting', href: '/services/coil-slitting' },
  { label: 'Cut-To-Length Service', href: '/services/cut-to-length' },
  { label: 'Luster Steel Processing', href: '/services/luster-steel-processing' },
  { label: 'Bulk Industrial Supply', href: '/services/bulk-industrial-supply' },
  { label: 'Delivery & Logistics Service', href: '/services/logistics-delivery' },
];
